### ISSUE TITLE
It would be better to have a bigger "Sign in" prompt 

### ISSUE THREAD

**Issue by hostmaster** [umputun/remark#1]
Hi, thank you for the invite. 

I was a bit struggled at the beginning because I did not find the sign in prompt. 
It is probably too small. It would be better to make it a bit more noticeable for a user. 

The screenshot is from Chrome macOS

Thank you. 
![remark42 demo 2018-05-12 11-08-24](https://user-images.githubusercontent.com/197788/39955286-d736c6b2-55d4-11e8-90db-997b90c005e7.png)

**Comment by igoradamenko** [comment]
Hey.

We've increased size of the prompt a bit, and made it bold.

Thank you :-)

<img width="752" alt="screen shot 2018-05-12 at 15 34 43" src="https://user-images.githubusercontent.com/6537798/39957353-36637f2a-55fa-11e8-8b5f-1f9f1f443ef5.png">
