### ISSUE TITLE
Remove useless polyfills

### ISSUE THREAD

**Issue by igoradamenko** [umputun/remark#102]
When we started to develop frontend part, we added [babel-polyfill](https://www.npmjs.com/package/babel-polyfill), because it was easy. Now I'm sure that we don't need all stuff that it contains.

Remark42 should support IE11+, Android 4.4.4+ and iOS 9+, so we need to check what polyfills are actually in use, and maybe if we don't use things like `Array.from`, `Object.assign`, etc, we can remove babel-polyfill at all. Or at least we can require just some parts of the package.

babel-polyfill is the heaviest package in our set now, and we need to fix it:

<img width="862" alt="screen shot 2018-06-23 at 21 28 41" src="https://user-images.githubusercontent.com/6537798/41812521-0ea8fbbe-772d-11e8-8ddf-5e75f4fcf64e.png">

**Comment by Guria** [comment]
I will take this issue.

**Comment by Guria** [comment]
Ok. I explored a bit. Automatic detection using babel-preset-env will reduce only 6kb for current browsers target:
![image](https://user-images.githubusercontent.com/36270/41816960-c06eed98-77a2-11e8-8364-b624bc3d48d9.png)
 And manual hunting to only used APIs will gain us about 11kb.
We can do go another way like [described in article](https://hackernoon.com/polyfills-everything-you-ever-wanted-to-know-or-maybe-a-bit-less-7c8de164e423): split polyfills into separate bundle and only load it for old browsers.
I also noted that we load 2 promise polyfills. One from core-js already with finally polyfilled and promise-polyfill that patched in user code. I think we should leave only core-js version. Will prepare PR to review soon,

**Comment by slawiko** [comment]
Previous I had an experience with [polyfill.io](https://polyfill.io/v2/docs/) and it is nice. But I need to say that one day their CDN was turned off for some reason, so our app wasn't able to work in IE.

**Comment by Guria** [comment]
Yeah. That the reason I decided to not to go that way. It also could slow down loading if network request will stale for some reason.
