### ISSUE TITLE
Add index.html with instructions

### ISSUE THREAD

**Issue by umputun** [umputun/remark#103]
_proposed by https://github.com/umputun/remark/issues/26#issuecomment-399681446_

We need a static HTML file with some details on how to integrate remark42, how to customize and so on. 

_related to #27_

**Comment by Guria** [comment]
@umputun could you create html stub that will be served by remark at root.
Currently it only serves WebRoot at `/web/`. I am not feel that I can extend routing config to serve single file at root myself.

**Comment by Guria** [comment]
I think I'll use serving a folder. Can you suggest how to make a redirect from root to '/getstarted'?

**Comment by umputun** [comment]
I can add routing from `/index.html` to `/web/getstarted.html` file. Can you keep it a single file?
