### ISSUE TITLE
Implement and document fully functional, local development environment

### ISSUE THREAD

**Issue by umputun** [umputun/remark#106]
To test (end-to-end) functionality locally, contributors need a simple way to deploy both backend and frontend. Currently, we have some description of how to bring local backend and emulate logged in users; however, this is used mostly by contributors of the backend side.

To make such local server frontend–friendly I'm going to add a new auth provider with two dev users:
- `devreg` (regular user permission) and `devauth` (admin permission). 

Then will need to describe how to setup such environment locally.

**Comment by umputun** [comment]
Added minimal but functional stand-alone setup. To bring it up run

```
docker-compose -f compose-dev.yml build
docker-compose -f compose-dev.yml up
```

It starts remark42 on http://127.0.0.1:8080 and adds local oauth2 provider "Dev". To access UI demo page http://127.0.0.1:8080/web

That `compose-dev.yml`also defines if logged user admin or not. By default, it will be the admin, and to switch it to regular user comment/remove `-ADMIN=dev_user`.

**Comment by umputun** [comment]
added an ugly form to select dev user in order to switch between admin and regular users.

**Comment by umputun** [comment]
@igoradamenko - you planned to add this info to README. Feel free to close this one as you done.

**Comment by igoradamenko** [comment]
@umputun, thank you for the reminder. I've added info about this testing env to the readme.

**Comment by Guria** [comment]
I tried to build on docker windows. It seems went ok. But I can't run it now:
```
PS C:\ws\misc\remark> docker-compose -f .\compose-dev.yml up
Starting remark42-dev ... done
Attaching to remark42-dev
remark42-dev | init
remark42-dev | execute /srv/start.sh
remark42-dev | prepare environment
remark42-dev | start remark42 server
remark42-dev | Usage: /sbin/su-exec user-spec command [args]
remark42-dev exited with code 0
```

**Comment by umputun** [comment]
most likely this is because you didn't define `USER` uid in your env. I have no clue about uid on win but the simplest way will be just to set it directly in `compose-dev.yml`, i.e. replace `- USER` by `- USER=1001`

**Comment by umputun** [comment]
for https://github.com/umputun/remark/issues/98#issuecomment-403754560 need to add the ability to show/set/select avatar

**Comment by umputun** [comment]
Select/upload avatar is to much trouble for dev user. Instead I have added GitHub-style automatic avatars. like this:

<img width="476" alt="7a74t-201807-10121719-2b0ar" src="https://user-images.githubusercontent.com/535880/42526520-b0003be2-843b-11e8-86b0-3b7bcb7efa73.png">
