### ISSUE TITLE
Vendor build dependencies

### ISSUE THREAD

**Issue by umputun** [umputun/remark#119]
Sometimes we have failed builds due to third-party modules/services. For example

```
Step 27/43 : RUN     cd /srv/web &&     npm i && npm run lint && npm run test && npm run build &&     rm -rf ./node_modules
 ---> Running in bd12192eb9f5
npm ERR! code EADDRNOTAVAIL
npm ERR! errno EADDRNOTAVAIL
npm ERR! request to https://registry.npmjs.org/chalk failed, reason: connect EADDRNOTAVAIL 2400:cb00:2048:1::6812:5f60:443 - Local (:::0)
```

This happens mostly on frontend build, but not always. Sometimes backend fails as it can't reach coveralls.

I would like to have our build dependencies fully vendored, i.e. it should be able to build everything without the internet connection. All optional steps, like coveralls, should not fail the build.

**Comment by umputun** [comment]
Coveralls was the only external dependency needed to run `build-backend` stage, made optional.

**Comment by umputun** [comment]
After discussion with @igoradamenko it sounds like such vendoring in js/npm world is not something usual unless proxy involved.

**Comment by Guria** [comment]
See #123
