### ISSUE TITLE
Find a proper way to polyfill promises

### ISSUE THREAD

**Issue by igoradamenko** [umputun/remark#122]
We use pofyfill from core-js/es6/promise, which is actually fine, but it doesn't work with `.all` and `.finally` in one chain:
![image](https://user-images.githubusercontent.com/6537798/42133012-51dbc7a0-7d2b-11e8-9885-b1847138aa89.png)

I've fixed it by returning the previous `.finally` polyfill in ed92a0bda5cc7922cdc0bcd552452a842c224d87, but right now it's strange, because we have two `.finally` polyfills in the bundle.

We need to find out a reason of the bug, and leave the only one solution.

**Comment by biggieman** [comment]
core-js 2.5.7 doesn't have finally in requires in es6/promise.js and in module code modules/es6.promise.js.

If you use `core-js/es7/promise` instead of `core-js/es6/promise.js` it will work fine in FF.
P.S. In core-js 3.0.0-beta `es` grouped in one.
