### ISSUE TITLE
Migrate from node-sass to postcss with nesting plugin.

### ISSUE THREAD

**Issue by Guria** [umputun/remark#135]
SASS features is not heavy used as I can observe.
Only nesting syntax is used and it could be easily achieved with postcss plugin.
Also I believe it is downloading of node-sass binary causes eventual build slowdowns mentioned in #133

**Comment by thepocp** [comment]
I think nesting plugin wrong solution because:
```
NOTICE: In v7.0.0 nesting at-rules like @media will no longer work, as they are not part of the nesting proposal.
```

**Comment by Guria** [comment]
@thepocp I already tested with https://github.com/postcss/postcss-nested 
Will bring it soon

**Comment by lexich** [comment]
Maybe the better way will be to use http://cssnext.io ?

**Comment by jackburg** [comment]
@lexich Looks promising.

**Comment by Guria** [comment]
@lexich @jackburg cssnext is deprecated and considered a bad practice. for now we just need to get rid of sass binary with minimal efforts and @thepocp already provided a pr #142 for that

**Comment by jackburg** [comment]
@Guria thanks for the clarification.
BTW: there had been not enough next in the cssnext and it was deprecated. :)
