### ISSUE TITLE
Comment area and Grammarly 

### ISSUE THREAD

**Issue by umputun** [umputun/remark#138]
For some reason [Grammarly](https://www.grammarly.com/) doesn't work for our comments.

For example:

- github 
<img width="408" alt="6pqek-201807-07131532-c6ems" src="https://user-images.githubusercontent.com/535880/42413517-e831fc86-81e7-11e8-9942-61e96c591d99.png">

- remark42
<img width="352" alt="2erj7-201807-07131507-uwqd5" src="https://user-images.githubusercontent.com/535880/42413523-fa741b5e-81e7-11e8-93f4-66938f69778c.png">

**Comment by Guria** [comment]
I guess it is because remark renders in an iframe.
See: https://support.grammarly.com/hc/en-us/articles/115000090392-I-do-not-see-the-G-icon-on-a-certain-web-page-or-in-a-certain-text-field-but-see-it-on-other-web-pages-

**Comment by umputun** [comment]
@Guria - does it mean we can't fix it or some smart workaround still possible?

**Comment by Guria** [comment]
Disqus doesn't work with Grammarly as well. Big chances that we can't fix it.
Though, I will investigate it a bit further.

**Comment by umputun** [comment]
@Reeywhaar & @sw-double maybe you guys have an idea how to deal with this? The issue is annoying for real and it is not just about Grammarly, the regular spellchecker doesn't work either (mac os, safari)

**Comment by Reeywhaar** [comment]
Grammerly doesn't work in iframe https://community.hubspot.com/t5/HubSpot-Ideas/Grammarly-Spell-Checker-Support/idi-p/175997

as for second it's can be easily solved by adding spellcheck attribute to input textarea actually

**Comment by umputun** [comment]
if we can have spellcheck it will solve 80% of the annoyance

**Comment by umputun** [comment]
spellcheck is working now, yay ;) Closing this one as we have no chance to convince Grammerly to work inside of iframe
