### ISSUE TITLE
Migrate from private drone to public travis

### ISSUE THREAD

**Issue by umputun** [umputun/remark#14]
I'd like to make build logs available for PR authors but don't want to keep it in my private drone. Travis seems to be the popular choice for such kind of things.

**Comment by comjf** [comment]
I've used travis-ci for a number of years (though on closed source projects). I'd be happy to help look into this task if you don't already have an owner.

Any funky notes about the way your testing? I plan to dig further into the source this week.

**Comment by umputun** [comment]
it will be very helpful, thx.

Nothing tricky in this build. Essentially it just runs docker build and pushes the image to docker hub. All tests as well as test coverage are the part of Dockerfile

**Comment by denji** [comment]
Build artifacts on `hub.docker.com` and integration public `travis-ci` will be very useful.

**Comment by AlekSi** [comment]
May you please enable repository here: https://travis-ci.org/umputun/remark? This will simplify life for people working on this issue. You may also enable "Build only if .travis.yml is present" so you don't receive bogus notifications.
