### ISSUE TITLE
Investigate strange block users select behavior

### ISSUE THREAD

**Issue by jackburg** [umputun/remark#148]
When you add both onBlur and onChange events listeners to the select in the block user control as it's advised by the JS linter (https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/no-onchange.md), to be friendly for keyboard only or screen reader users, you'll get into trouble:

1. If we simply add onBlur to the element (both onBlur and onChange are present), we'll get an infinite event loop in the case when the user clicks Cancel button in the confirmation dialog.

![2018-07-09 13 55 50](https://user-images.githubusercontent.com/7156424/42450473-f788af76-838c-11e8-8648-5efdaec46078.gif)

2. If we set onBlur instead of onChange, we broke user experience because our app is now aware of changes happened in select only when onBlur event occurs — user should make a selection and then click somewhere else to actually trigger the event.

![2018-07-09 13 53 31](https://user-images.githubusercontent.com/7156424/42450491-0277e0dc-838d-11e8-922f-604343c4577f.gif)

We should investigate this issue further to be more welcome for users with remotes, keyboards and for users with a screen readers.

**Comment by Reeywhaar** [comment]
Fixed in #272
