### ISSUE TITLE
Email notifications for new commentaries?

### ISSUE THREAD

**Issue by outcoldman** [umputun/remark#15]
Is there are an option to subscribe with an email to all new commentaries for a specific page? Disqus had this option.

**Comment by outcoldman** [comment]
As an alternative, maybe an RSS feed for all the commentaries from the website? I like to subscribe to most of the posts on radio-t.

**Comment by umputun** [comment]
RSS actually is a very nice alternative, thx for the idea.

**Comment by umputun** [comment]
basic support of [rss feed](https://demo.remark42.com/api/v1/rss?site=remark&url=https:%2F%2Fremark42.com%2Fdemo%2F) available on demo site. No UI side yet.

take a look as I'm not sure what exactly we should have in this feed. For now, I have added full comment text to descriptions.

**Comment by umputun** [comment]
makes sense. changed.

**Comment by outcoldman** [comment]
```
curl 'https://demo.remark42.com/api/v1/rss?site=remark&url=https:%2F%2Fremark42.com%2Fdemo%2F'
404 page not found
```

**Comment by umputun** [comment]
`curl 'https://demo.remark42.com/api/v1/rss/post?site=remark&url=https:%2F%2Fremark42.com%2Fdemo%2F' will do

**Comment by outcoldman** [comment]
@umputun to make it clear - is it an RSS for one page or whole website? 
I would prefer to have it return commentaries from the whole website (all new commentaries on radio-t).
In that case, the title probably should be a something like `{user} replied on {page title}`.

**Comment by outcoldman** [comment]
and show only last N

**Comment by umputun** [comment]
this is `/post`, i.e. for one post/page. The initial request was "subscribe with an email to all new commentaries for a specific page?". Adding for all posts won't be a problem

**Comment by umputun** [comment]
this is for everything - `http "https://demo.remark42.com/api/v1/rss/site?site=remark"` Both limited to 20 last updates

**Comment by igoradamenko** [comment]
We've added links to RSS to UI :-)
