### ISSUE TITLE
Bugs/Improvements in Last comments windget

### ISSUE THREAD

**Issue by akosourov** [umputun/remark#151]
![image](https://user-images.githubusercontent.com/17426217/42492606-2b293106-8433-11e8-87b8-a3cbf83e7488.png)

1. When I open user's last comments widget I see comments and votes for them. But I'm not allowed to vote and a title shows me that "Yout can't vote for your own comments". But they are not my own comments.
2. I don't uderstand why user-id is shown to user. In my opinion it is an internal information and should be hidden.
3. Cache invalidation improvements. If someone votes to a user, and then I open last comments widget I don't see this vote

UPD:
![image](https://user-images.githubusercontent.com/17426217/42552560-5c06ca18-84f6-11e8-8c72-192a406ccb86.png)

4. Username shows as url encoded text
5. Close button intersects with username

**Comment by umputun** [comment]
both 1 and 2 are frontend. pinging @Guria 

For user-id shown here - yeah, agree. It used to be the only info we had on dbl-click on username, and it has some valid use cases for both admins and regular users. But we should hide it better.

**Comment by akosourov** [comment]
Could you explain use cases for user-id? (from regular user's side) For me it shows only from what provider user came (github, facebook, etc)

**Comment by Guria** [comment]
1. I am afraid quick fix could be tricky. Should be eliminated with #95 
2. Just tell us what to do with it

**Comment by akosourov** [comment]
>One of the practical examples will be verification request. Another one - support request, like user asking "why my comments are not showing up?". It also has some value to resolve possible collisions and detect fake identity. In all of these cases username won't be enough and something unique needed.
@umputun ok, got it, thanks

**Comment by umputun** [comment]
@Guria - one of the solutions can be not to show userID by default in this info panel and make it visible only as user click on the name

**Comment by akosourov** [comment]
I've editted the issue and added 4,5 points

**Comment by umputun** [comment]
there more visual issues:

- we need a visual separator between the header section (with user info) and the list of comments. Not sure what the right way - different background or just `<hr>`
- time alignment
- some visible separator between comments

<img width="230" alt="9kl43-201809-02134731-sc7kw" src="https://user-images.githubusercontent.com/535880/44959603-decc1e00-aeb6-11e8-87f3-b64678956302.png">

This is an example of disqus` last comments. We don't need that fancy but ours looks too minimalistic.
<img width="333" alt="dfg3t-201809-02135026-8ayh6" src="https://user-images.githubusercontent.com/535880/44959628-38344d00-aeb7-11e8-9a50-7b5a06b11001.png">

**Comment by Reeywhaar** [comment]
I consider this fixed, as there no more major layout bugs
