### ISSUE TITLE
Improve UX of login flow

### ISSUE THREAD

**Issue by cooperaj** [umputun/remark#157]
Currently, after logging in at the oauth provider of your choice you get redirected back to the remark iframe. This doesn't contain your site but an extrawide (if on a desktop) commenting box. This briefly flashes up and then you are redirected to the page proper. 

It would be better if you could avoid the flash of content perhaps by hiding the comment box during the auth flow?

**Comment by Guria** [comment]
Looking into it right now. Thanks for opening issue

**Comment by Guria** [comment]
You can check it now on https://remark42.com/demo
