### ISSUE TITLE
Dev oath provider callback url is hardcoded

### ISSUE THREAD

**Issue by Guria** [umputun/remark#159]
Dev Oauth provider should respect REMARK_URL variable

**Comment by umputun** [comment]
Any practical reason why we should care?

**Comment by Guria** [comment]
I suppose a developer might have strong reasons to change host/port in a local environment.
And it would definitely confuse when faced with broken auth flow.

Or even better just use original browser referrer to return back.
It very annoying to have auth problems just because you opened localhost instead of 127.0.0.1.
Also, it would simplify Webpack Dev Server setup since it would run in parallel on another port.

**Comment by Guria** [comment]
Thanks, that was super fast :)
