### ISSUE TITLE
Allow CORS for get requests

### ISSUE THREAD

**Issue by Guria** [umputun/remark#160]
Currently, last-comments.js and counter.js would fail to fetch data from remark instance that requires a cross-domain request.
We can fix it by setting `Access-Control-Allow-Origin: *`  response header for all get requests.

It doesn't affect the main widget because it's loaded in an iframe with the same origin as remark instance.

**Comment by umputun** [comment]
We don't have CORS directly on the backend, however, demo site does some CORS on nginx level:

```
        #CORS
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, PUT, POST, DELETE, OPTIONS';
        add_header Access-Control-Allow-Headers "Content-Type, Authorization, X-Requested-With";
        if ($request_method = 'OPTIONS') {
             add_header 'Access-Control-Allow-Origin' '*';
             add_header 'Access-Control-Allow-Methods' 'GET, PUT, POST, DELETE, OPTIONS';
             add_header 'Access-Control-Max-Age'        86400;
             add_header 'Access-Control-Allow-Credentials' 'true';
             add_header 'Access-Control-Allow-Headers' 'Authorization,DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Cont
             add_header 'Content-Length' 0;
             add_header 'Content-Type' 'text/plain; charset=UTF-8';
             return 204;
         }
```

@Guria - are you proposing to move it to the backend?

**Comment by Guria** [comment]
I see your point that it belongs to nginx setup. As for me, I faced with problem while testing on local setup.
If you believe that app shouldn't be aware about cors headers, we can leave it as is and just document necessity of additional setup on nginx or whatever.
And, not neccessary, but would be nice, if we can solve it at least for local testing.

**Comment by umputun** [comment]
local setup is the valid point. Another valid point - backend should serve fronted without any help (extra setup) and mandatory nginx CORS config breaks this promise.

Do you know what exactly the minimal set of cors headers you need? Probably we can dynamically control 'Access-Control-Allow-Origin' some day and allow access from the real origins only. Currently, we don't know where consumer located, and for now `*` should be fine. You said "response header for all get requests", does it meant the only thing frontend needs is ` add_header 'Access-Control-Allow-Methods' 'GET` ? Probably we will have to allow `X-XSRF-TOKEN` and `X-JWT` headers as well. Anything else you can think about?

**Comment by umputun** [comment]
@Guria I have added cors to `feature/cors` branch, pls see/try if it makes frontend happy for local testing. The code https://github.com/umputun/remark/blob/feature/cors/backend/app/rest/api/rest.go#L121 allows all request types. You can play with this and see what the minimum level you actually need.

**Comment by Guria** [comment]
@umputun just tested `feature/cors` and all seems working now.
