### ISSUE TITLE
Change vote buttons order 

### ISSUE THREAD

**Issue by alehano** [umputun/remark#162]
It would be more convinient if upvote arrow button will be on the right side. Upvote uses more often than downvote. Now it placed close to collapse button that sometimes cause accidentally wrong clicks, especially on mobile phone.

**Comment by umputun** [comment]
I don't think swapping them will be a good idea as it will confuse existing users for sure.

Regarding accidental click on the collapse button - I don't like this position either but not sure what will be the better place.

@Guria - any bright ideas?

**Comment by Guria** [comment]
@umputun I like Reddit solution: border on the left through all nested thread

**Comment by alehano** [comment]
@Guria Agree, collapse button on the left side is more intuitive.

**Comment by umputun** [comment]
@Guria reddit-style collapsing should be fine

**Comment by umputun** [comment]
@sw-double & @Reeywhaar - making comments collapsable on the border line we just added can be useful 

re: #350

**Comment by paskal** [comment]
I wonder what are the action items here after #545 is merged?

**Comment by WinstonPoh** [comment]
What if the upvote button is changed to be on top of the number and downvote at the bottom of the number? That was both new and old users will not be confused?
