### ISSUE TITLE
Add auth handling to deleteme.html page

### ISSUE THREAD

**Issue by Guria** [umputun/remark#170]
#109 introduced new page deleteme.html that finishes approval of `deleteme` request by admin.
The problem is that we assume that admin is already logged in when clicking the link from an email.
We need to show current user login there, controls to signin / signout and a button to actually send deleteme request.

**Comment by umputun** [comment]
I don't think we even need to show the current user login. The only function we have to enforce - if the user is not admin (or not logged in) ask him to log in as admin.

**Comment by Guria** [comment]
resolved by #208
