### ISSUE TITLE
Comments area scroll only horizontally with middle mouse button in Firefox.

### ISSUE THREAD

**Issue by krab** [umputun/remark#175]
![s0phksx](https://user-images.githubusercontent.com/834046/43048753-64cd1e24-8df5-11e8-9f48-5c6677c3140f.png)

Also adds a lot of empty space https://i.imgur.com/mk4Se5J.png
Outside of comments area, everything scrolls fine. https://i.imgur.com/VVt3jay.png

**Comment by Guria** [comment]
Please check if it reproducible on https://remark42.com/demo 
I bet it already fixed.

**Comment by krab** [comment]
Looks like it fixed, just not updated on radiot website.
