### ISSUE TITLE
Focusable elements outline looks odd

### ISSUE THREAD

**Issue by Guria** [umputun/remark#187]
We need a consistent and well-looking focus indicator for controls.
Default browser outline is too odd for most mouse / touch users.

**Comment by Clearic** [comment]
I agree, focus-ring on control elements looks weird. In my projects to solve this problem, I use [focus-visible polyfill](https://github.com/WICG/focus-visible). What it does is it hides outline when you interact with controls using a mouse, but outline still appears when using a keyboard. Thus we get best of both worlds, mouse users don't see the focus-ring and the site remains accessible by keyboard.

What do you think about this solution?

**Comment by Guria** [comment]
Yeah, we can try it. Does it play nice with React / Preact?  Anyway, PR is welcome

**Comment by Clearic** [comment]
It works absolutely fine with React. Tomorrow I'll prepare PR.

**Comment by umputun** [comment]
@Guria - is this one done? LGTM

**Comment by umputun** [comment]
I'm not sure what are "elements" here. The only one I see is "X" on last comments, and this one looks good. One minor inconsistency - it can't be closed by Esc, but if this is a big deal we can postpone this part

**Comment by Clearic** [comment]
> One minor inconsistency - it can't be closed by Esc

The UserInfo can't be closed by Esc right now, because there is a bug. I'll fix it.

**Comment by igoradamenko** [comment]
It works right now, thanks @Clearic.
