### ISSUE TITLE
Integrate LE certificate support

### ISSUE THREAD

**Issue by umputun** [umputun/remark#191]
The goal is to allow HTTPS with automatic Let's Encrypt certificate without a need of an external proxy. In addition, we should accept existing certificates.

**Comment by umputun** [comment]
@akosourov want to take this one? Generally, for LE support we need some ACME library and wire it to REST. In addition, we will have to expose both http and https from the container and, after successful registration, enforce http>https redirect.

I think there are multiple projects doing this sort of things already and it should not be too hard.

**Comment by umputun** [comment]
sure, take your time and feel free to ask. Probably `golang.org/x/crypto/acme/autocert` is the one you want. Take a look on [HTTPS for free in Go, with little help of Let's Encrypt](https://blog.kowalczyk.info/article/Jl3G/https-for-free-in-go-with-little-help-of-lets-encrypt.html) or/and [Free and Automated SSL Certificates with Go](https://goenning.net/2017/11/08/free-and-automated-ssl-certificates-with-go/)

**Comment by akosourov** [comment]
Ok, thanks for materials!

**Comment by akosourov** [comment]
@umputun Last week didn't give a chance to start doing it (no free time), but current seems to be ok :)
I want to ask whether I understand implementations details correctly.
I see that steps (from high level):
1. Add additional param which says whether we should run https server or not. 
2. If https param is set make new https server with acme support and embed https server in a Rest struct (add `httpsServer`). 
3. To run https we need to set [HostPolicy](https://github.com/golang/crypto/blob/master/acme/autocert/autocert.go#L108) for better security. Would it be correct if I use `url` param and strip `https://`?
4. Move current router from http to https server and set http -> https redirect. I see acmee library can do it [itself](https://github.com/golang/crypto/blob/master/acme/autocert/autocert.go#L359)
5. And don't forget to add posibility to accept existing certificate

**Comment by umputun** [comment]
We have a way to know if the server http or https already (`RemarkURL` parameter) but we won't know if it is internal or via proxy. So yeah, some parameter needed. I'd suggest `RemarkSSL` with 3 choices - `auto`, `static`, `none`.

> To run https we need to set HostPolicy for better security. Would it be correct if I use url param and strip https://?

yeah, I think so

> Move current router from http to https server and set http -> https redirect

Not really, because https is not mandatory. We should be able to serve http the way we do it now and switch to https if defined in flags.

> And don't forget to add posibility to accept existing certificate

This part probably will need an extra mapping (on compose level), and two new flags for key and cert.

**Comment by umputun** [comment]
@akosourov I have checked coverage reports and realized some SSL related branches not covered at all. 

- https://coveralls.io/builds/20279842/source?filename=backend%2Fapp%2Frest%2Fapi%2Frest.go#L85
- https://coveralls.io/builds/20279842/source?filename=backend%2Fapp%2Frest%2Fapi%2Fssl.go#L85

Will be nice to cover this code with tests

**Comment by akosourov** [comment]
Sure, I will be glad to add them. Didn't pay attention on it. I'll add
