### ISSUE TITLE
I can give two votes for a single comment

### ISSUE THREAD

**Issue by hostmaster** [umputun/remark#2]
I can vote twice for a single comment. 
the screen record is attached. (it is zip b/c GH does not allow video attachments) 
[voting.zip](https://github.com/umputun/remark/files/1997394/voting.zip)

**Comment by igoradamenko** [comment]
It's not a bug. In your video you already have comment downvoted. Then you upvote it, it resets your downvote. And then you upvote it.

It would be a double vote, if you changed comment score by 2 (to any “side”). But you first decrease it by 1, and then increase by 2. So total change is 1.

**Comment by hostmaster** [comment]
@igoradamenko My bad. I'm sorry You're absolutely right 👍🏻
