### ISSUE TITLE
As a user I would like to remove my own comments

### ISSUE THREAD

**Issue by m1ndful** [umputun/remark#200]
I haven't found a way to remove my own comments as a non-admin user.
Is this something you are planning to add?

**Comment by umputun** [comment]
Currently, the only way to "remove" comment is to edit with empty (or "del") text. Probably I can add a new call for this with the same time restrictions as edit functionality. 

However, as far as I know, such removal functionality is not that usual for commenting systems, and I'm not sure if such functionality really needed.

**Comment by umputun** [comment]
I have added `delete` flag to the current request (json) used by `PUT /api/v1/comment/{id}`

Now we need frontend support for this

**Comment by m1ndful** [comment]
> Currently, the only way to "remove" comment is to edit with empty (or "del") text.
It doesn't really work, because once you hit on your username, it will show you history of changes.

**Comment by umputun** [comment]
not sure what you mean, this is part of the current edit functionality, nothing special about this particular edit, just different text. In 5 minutes window user can edit a comment by clicking on "Edit" link, not the username.

**Comment by umputun** [comment]
in case you meant a way to remove all comments, this is in place already, i.e. user can request complete removal of all comments by clicking on "Request my data removal" 

<img width="399" alt="fvd70_20180907_144240 yh5m8" src="https://user-images.githubusercontent.com/535880/45239862-58478000-b2ac-11e8-94a6-ab67508724cb.png">

**Comment by m1ndful** [comment]
@umputun , looks like latest docker image is not in sync with master branch.

**Comment by umputun** [comment]
if by latest you mean label `:latest` - sure, it is not from master but from tagged release. The one from master is `:master`, see https://hub.docker.com/r/umputun/remark42/tags/
