### ISSUE TITLE
Restrict max/min vote counts

### ISSUE THREAD

**Issue by umputun** [umputun/remark#207]
In order to prevent comment's vote section from growing too large, it makes sense to limit the maximum number of elements and ignore/rejects attempts to add another vote. This could be some configurable max with some sane default, like 1000 or so.

**Comment by Reeywhaar** [comment]
Maybe rather apply transform to score to become like `1k`, `1.5k` `1m`? The `title` attribute could show precise number of votes. Then it's just a frontend issue.

**Comment by umputun** [comment]
The issue is not how to show, but how to restrict the list of [`Votes`](https://github.com/umputun/remark/blob/master/backend/app/store/comment.go#L20) (technically speaking not list but map) in comments. Each key here is a unique user ID and the value indicates +/-.
