### ISSUE TITLE
Set focus on comment text box after Reply button

### ISSUE THREAD

**Issue by shalugin** [umputun/remark#21]
It would be convinient

**Comment by shalugin** [comment]
Firefox 60

От: Igor Adamenko
Отправлено: 14 мая 2018 г. в 10:20
Кому: umputun/remark
Копия: Aleksandr Shalugin; Author
Тема: Re: [umputun/remark] Set focus on comment text box after Reply button(#21)

But we already do it. What browser do you use?

**Comment by igoradamenko** [comment]
I can't reproduce this bug in FF60. Add a video/gif proof, please, if it's possible.

But now I close this issue.

**Comment by shalugin** [comment]
It works now.

**Comment by rakleed** [comment]
@umputun @akellbl4 it doesn't work again. Checked in Chrome 92 and Firefox 90 at https://remark42.com/demo/ and [radio-t.com](https://radio-t.com/p/2021/07/20/prep-764/#comments).
