### ISSUE TITLE
Selection of sorting is not persistent 

### ISSUE THREAD

**Issue by umputun** [umputun/remark#215]
Every time I close safari the sorting reset to the default (best) and `__remarkSort` disappears from the local storage.

**Comment by deril** [comment]
I'm using Safari Version 12.0.1 (14606.2.104.1.1) and cannot reproduce the issue. I close the tab, close browser and after that I can see `__remarkSort` option in local storage.

**Comment by Reeywhaar** [comment]
@deril the bug above reproducible if you have `prevent cross-site tracking` on or disabled third-party cookies in safari's preferences. Also remark's page should be loaded in iframe. Safari treats localstorage of an iframe as a sessionStorage and wipes it on exit.

This is safari's anti-tracking 'feature': https://bugs.webkit.org/show_bug.cgi?id=168631

I'm using `12.0.1 (13606.2.104.1.2)`, maybe they fixed it, which I highly doubt.

**Comment by igoradamenko** [comment]
I moved sorting key from LS to cookies in e09678c. It must work fine now.

**Comment by Reeywhaar** [comment]
Works for me

**Comment by umputun** [comment]
yep, it works
