### ISSUE TITLE
Warning in console

### ISSUE THREAD

**Issue by dernasherbrezon** [umputun/remark#22]
No idea what doest it mean:

```
[Warning] Possible Unhandled Promise Rejection: – TypeError: undefined is not an object (evaluating 'O.locator.url') (remark.js, line 7)
TypeError: undefined is not an object (evaluating 'O.locator.url')
```

**Comment by igoradamenko** [comment]
There is not enough information. How did you get it? Why do you think that's important?

**Comment by dernasherbrezon** [comment]
Steps to reproduce:
1) Open "https://remark42.com/demo/" (safari latest)
2) Type in "  test"
3) Check console.

This is warning,  might not be important.

**Comment by igoradamenko** [comment]
I can't reproduce it :-(

Let's think that it's not important, yep.
