### ISSUE TITLE
[BUG] View of user comments is broken

### ISSUE THREAD

**Issue by Hixon10** [umputun/remark#229]
Steps to reproduce a bug:
1) Go to https://radio-t.com/p/2018/12/15/podcast-628/#remark42
2) Press on some user nickname. For example. press on `Valeriy Kischenko`
3) You can see a bug

https://snag.gy/MptTcK.jpg

P.S. Bug is reproduces on latest Firefox/Chrome

**Comment by umputun** [comment]
this bug effect introduced by #228, I guess unexpected side effect.
@igoradamenko - probably dark side leaked into light theme ;)

**Comment by igoradamenko** [comment]
Yeah, my bad, sorry :-)

Fixed in 59ed9bb9a445076c60cdb85d72e86de5b1e45957 & b7f1b2a6092798cdf9357239f923c115e26f1199.

I've checked fix on demo (https://remark42.com/demo/) and it works fine now.
