### ISSUE TITLE
Неясное поведение после переполнения количества символов в форме комментария

### ISSUE THREAD

**Issue by AnikoV** [umputun/remark#23]
После переполнения количества символов, дальше форма позволяет вводить только некоторые спец. символы, например число пи (π), а также кириллицу. При этом счётчик уходит в минус, что вроде нормально. В превью и публикацию все уходит корректно обрезаное. Просто сам факт того, что после переполнения можно вводить только некоторые символы сбивает с толку. "Вы либо штаны оденьте, либо крестик снимите" ©umputun  )))
P.S. тестировал со смартфона на android

**Comment by umputun** [comment]
@AnikoV - pls try to use English for your comments and issues. thx.

**Comment by igoradamenko** [comment]
It's duplicate of #3.

**Comment by AnikoV** [comment]
@umputun Ok got it.
