### ISSUE TITLE
Votes change enabled for read-only posts

### ISSUE THREAD

**Issue by umputun** [umputun/remark#230]
Not a big deal but feels wrong. I tend to believe it is not handled correctly on both backend and frontend sides. I'll take care of backend, but need someone to disable it on the frontend.

**Comment by umputun** [comment]
this was done for the backend and any votes on RO posts now rejected. Need UI side to adopt.

**Comment by Reeywhaar** [comment]
Anyone at it? May take.

**Comment by umputun** [comment]
sure

**Comment by Reeywhaar** [comment]
Noticed that server allows to vote on posts disabled manually. Is it intentional? Can I rely on `info.read_only` value?

**Comment by umputun** [comment]
>  Is it intentional?

no, I  just missed this one.

> Can I rely on info.read_only value?

yeah. I think it already does the check to hide edit controls on RO post. The same thing should be done for arrows as well
