### ISSUE TITLE
Add support of post titles

### ISSUE THREAD

**Issue by umputun** [umputun/remark#241]
This is mostly for the last comments widget, but also usable for notifications as well. The goal is to keep title (page title) as a part of the comment and display them.

**Comment by igoradamenko** [comment]
@umputun, looks like it works :-)

**Comment by umputun** [comment]
kind of, sort of ;) We need a few more things:

- ability to reset (set) titles in some "batch migration"
- restore links on names if no title (back compatibility)
- remove hover on non-linked names

**Comment by Reeywhaar** [comment]
Nice to have titles in user comments sidebar as well.

**Comment by umputun** [comment]
@Reeywhaar feel free to PR ;)
