### ISSUE TITLE
Comments with replies should be non-editable

### ISSUE THREAD

**Issue by umputun** [umputun/remark#248]
Currently, the only limit for comment's edit is a time window. However, editing or deleting the comment after a reply to it looks very confusing. We should disable/rejects such edits on the backend side.

**Comment by umputun** [comment]
I have added a check on my side and rejection. However, UI should treat such comment as read-only the same way it does based on the time window. Hopefully, it can be easily detected if any child comments/replies and hide edit and delete links.

@Reeywhaar - wanna take a look?

**Comment by Reeywhaar** [comment]
@umputun will be glad to help, but not as early as tomorrow

**Comment by umputun** [comment]
thx

**Comment by Reeywhaar** [comment]
Am I understading right that if comment has reply from the same user it's still editable?

**Comment by umputun** [comment]
this feels like a bug on my side. Probably I'll just switch any comment with any reply to RO
