### ISSUE TITLE
Vote buttons when logged out

### ISSUE THREAD

**Issue by Arelav** [umputun/remark#249]
Looks like vote buttons should be hidden when the user is not logged in.
I tried to vote on few comments and nothing happen. Then I get it's not logged in yet.

I see two options:
* to hide vote buttons when the user is not logged in.
* to show a modal window with the message like "Only logged in users can vote. Please login first"

**Comment by umputun** [comment]
we already show disabled icon and the message:

<img width="381" alt="emcow-201901-16143617-p99y1" src="https://user-images.githubusercontent.com/535880/51277099-3ff31a80-199c-11e9-92ba-9139465a637e.png">

probably we could just disable arrow's highlight for such cases.

**Comment by Arelav** [comment]
Yes, you are right.
I missed the cursor change. The error icon changes the colour on mouseover and I missed that cursor also changes it's confusing a bit.
If the css solution used to change cursor maybe the good Idea will be to disable :hover css rule for not logged in users. And looks it's planned to use other icon according to the `remark/web/app/components/comment/__vote/_disabled/comment__vote_disabled.scss`

I'll try to find a time to take a look deeper. What's behaviour do you prefer? Is it ok to highlight the arrow only for logged in users?

**Comment by umputun** [comment]
> Is it ok to highlight the arrow only for logged in users?

yes

**Comment by Arelav** [comment]
I made PR. I'm sorry I have no ability not to clone and setup hole project. I checked in the browser and also make sure the generated CSS from the scss file it's what I tested.

**Comment by umputun** [comment]
Fixed by #251
