### ISSUE TITLE
Telegram integration doesn't allow to send direct messages

### ISSUE THREAD

**Issue by VaultVulp** [umputun/remark#255]
Current integration allows sending messages only to public channels with `@ChannelName`-syntax. 

I guess it may be more useful to support direct messages and private channels. As described [here](https://core.telegram.org/bots/api#sendmessage) you can initialize the value of the `chat_id` parameter with integer id of a channel or user.

I suggest removing the code that prefixes any `chat_id` value with the `@` character before the payload is sent to the telegram API. It will allow developers to set any value (`@ChannelName` or `123455`) via the provided `NOTIFY_TELEGRAM_CHAN` environment variable.

If this proposition will be accepted, following file may be updated: [backend/app/notify/telegram.go](https://github.com/umputun/remark/blob/master/backend/app/notify/telegram.go). I suggest to remove both the trimming of the `@` prefix (line 33) and the addition of the `@` character in the process of API URL generation (line 95).

**Comment by umputun** [comment]
Theoretically, such flexibility sounds like a good idea, but I don't see a practical use case for notifications to private channels and direct messages. What kind of setup you have in mind for such notifications?

**Comment by VaultVulp** [comment]
I think it may help with the following problems:
- each user can only have a limited number of public channels/group names reserved for him, as of today, no more than 8 public names can be created.
- it will allow users to create a private source of notifications, in case they set up discussion platform in their internal network or behind some authentication wall, and receive notification w/o the fear of exposing their communication to someone.

Truth be told, I prefer to receive notification from my services via the private channel with my bot, and, as far as I know, multiple senders can send messages with the same token, so I would like to reuse the same token with the Remark and receive aggregated notifications through one source.

**Comment by umputun** [comment]
> each user can only have a limited number of public channels/group names reserved for him, as of today, no more than 8 public names can be created.

Makes sense. I didn't know about 8 pub channels limitation

> it will allow users to create a private source of notifications, in case they set up discussion platform in their internal network

Such use case supported by remark42 partially. Currently, auth is oauth2 only. However, I can imagine firewalled instance allowing oauth2 only and limiting everything else.

The bottom line - I can see how the proposed change can be helpful. If you planned PR, pls proceed.
