### ISSUE TITLE
Positive-only voting score (optional)

### ISSUE THREAD

**Issue by umputun** [umputun/remark#260]
The idea is to limit the voting result to positive values only. It doesn't mean allowing +1 votes only, but to prevent the final score from being negative. In other words, API will not accept -1 vote if the score <= 0

The proposed change will be optional with some new parameters and, by default, it will be off. Actually, we can generalize it a little bit by defining `MIN_SCORE` param. Another thing we can do - allow such thing per post to overwrite the site's default `MIN_SCORE`. 

I can see some practical use cases for this:
- prevent negative scores on the comments which act as "proposals"
- make users feel better on some sensitive topics 
- prevent a chain of downvotes "on red". I.e. some users see others downvoted the comment and tend to do the same.

Any opinions?

**Comment by umputun** [comment]
cc @igoradamenko @Reeywhaar

**Comment by igoradamenko** [comment]
I think it's better not to show negative scores to everyone except an author. I mean, if anyone has score < 0, he can see it, but anybody else can't. They see only '0'. Just to prevent downvotes “on red”.

I think it's better because author can see the truth. And it's good when people can downvote if they want to. I'm not sure that we are allowed to decide who can vote and who can't. ¯\_(ツ)_/¯

**Comment by umputun** [comment]
> Basically what is needed from backend is to add min-score/max-score field to /api/v1/config?site= response

This may not be enough as it will be all-or-nothing only. If we want to allow switching some particular posts to such "positive" mode min should be part of `PostInfo`

**Comment by Reeywhaar** [comment]
@umputun or like that, but this get things complicated. How to mark post as upvote-only? It's easy, just add button to admin section, next to "disable comments". But how to mark some posts category automatically? It can be via, idk, regex in env. There should be some settings hierarchy `global->per-category->per-post` then.

**Comment by umputun** [comment]
I think the part if how to assign upvote to a group is outside of the scope for now. We can start with a simple implementation like we do for RO.

**Comment by Reeywhaar** [comment]
so ping then, when backend is ready

**Comment by umputun** [comment]
added backend support, site-level for now. `/config` returns a new flag `positive_score` if this mode active.

**Comment by umputun** [comment]
I don't like the idea of likes only, i.e. without dislikes and I think the current ticket addresses concerns I have listed above. 

For the "report" button - this is something useful but certainly outside of the ticket.  Currently, we don't have a way to send direct notifications in any form or shape, and the closest method for this is to generate some admin-notifications RSS and/or telegram notifications. I'm planning to implement email notifications too, but as of now, there is nothing like this in the code,

**Comment by Reeywhaar** [comment]
With `POSITIVE_SCORE=true` any attempt to upvote `PUT /api/v1/vote/facb6542-899a-4d2c-aa4c-1db3bccd302c?url=https://remark42.com/demo/&vote=1&site=remark HTTP/1.1` resolves in
```
HTTP/1.1 400 Bad Request

{"details":"can't vote for comment","error":"minimal score reached for comment facb6542-899a-4d2c-aa4c-1db3bccd302c"}
```

I don't see this error without `POSITIVE_SCORE=true`

Take a look when have a free time.

PS: Btw, I thought you were gonna make it on "per-post" basis, so there will be like `PUT /api/v1/admin/positive_score?site=site-id&url=post-url&positive_score=1` endpoint, what changed your mind?

**Comment by umputun** [comment]
the bug was fixed.

> you were gonna make it on "per-post" basis ... what changed your mind?

Laziness, mostly ;) Eventually I'll make it post-based
