### ISSUE TITLE
Counter is mistaken in counting comments

### ISSUE THREAD

**Issue by OnlineBiblioTK** [umputun/remark#261]
After adding a single comment and deleting it, the counter returns 1 for this page.

**Comment by umputun** [comment]
@Reeywhaar could you add both counter and last comment widget to a dev page we have? It will help to check issues like this right away

**Comment by OnlineBiblioTK** [comment]
UPD: Error occurs when user deletes own comment, not admin

**Comment by umputun** [comment]
@OnlineBiblioTK - thx for the report, it helped to fix an interesting cache related issue. Should be fine now, I'll consider bugfix release as soon as done with #262 

@Reeywhaar - thx for the help.

**Comment by OnlineBiblioTK** [comment]
Thank you for your work
