### ISSUE TITLE
"Disable comments" on the page where there are no comments initially

### ISSUE THREAD

**Issue by OnlineBiblioTK** [umputun/remark#262]
If the admin clicks "Disable comments" on the page where there are no comments, the option does not switch to "Enable comments", the input window is not removed. With each click, in the logs we get "......&ro=1".

However, it is no longer possible to add a comment on this page, we get "Something went wrong. Please try again a bit later".

**Comment by umputun** [comment]
@Reeywhaar @igoradamenko - I think smth with ui goes a little bit crazy here

**Comment by Reeywhaar** [comment]
ui goes crazy because if post is marked readonly and there are no comments `/api/v1/find?url=https://remark42.com/demo/&sort=-active&format=tree&site=remark` respond with
```
{"details":"can't find comments","error":"no bucket https://remark42.com/demo/ in store"}
```
While if there at least one comment and post is read-only the response would be
```
{"comments":[▋▋▋▋▋▋▋▋▋],"info":{"url":"https://remark42.com/demo/","count":1,"read_only":true,"first_time":"2019-01-25T16:16:14.7060253-06:00","last_time":"2019-01-25T16:16:14.7060253-06:00"}}
```

So, in first case ui don't know if post is read-only so it can't change button to `enable comments` because there is no `info.read_only` in response

**Comment by Reeywhaar** [comment]
yep, ui side is broken now, loading spinner and nothing more.
![screenshot 2019-01-26 at 03 33 57](https://user-images.githubusercontent.com/884649/51779888-3d6e8e80-211b-11e9-910b-6c5154756d54.png)

**Comment by Reeywhaar** [comment]
Right now `/api/v1/find` returns `{comments: null, info: {...}}` and `null` is unexpected value for comments. I'll add check for `null` but I think it's better to set comments to empty slice by default on the backend too

**Comment by umputun** [comment]
I have fixed find response, however not sure why last affected as I didn't touch it. Probably it always returned null on empty comments. Anyway, made it to return [] as well

**Comment by umputun** [comment]
@Reeywhaar - if this change working as you expect we could probably drop #264 ?

**Comment by Reeywhaar** [comment]
Last time the response was treated like error which has been caught, and handled by return of default placeholder data instead.

Let me see, if everything works, and if so, I'll drop

**Comment by Reeywhaar** [comment]
So, yes, everything works good regarding comments.

As for last comments there are errors in console, which I think rather ugly :-) From ui point as I said it's just an empty widget. If you can change response to be `[]` would be great.

![screenshot 2019-01-26 at 08 05 51](https://user-images.githubusercontent.com/884649/51782907-9ea95880-2141-11e9-9fa1-b3f4795954ad.png)
