### ISSUE TITLE
email notifications

### ISSUE THREAD

**Issue by umputun** [umputun/remark#265]
see #15 

I would like to implement a generic way to notify by email with customizable providers. This will require users to enter the email and we will have to store it somehow and associate with the user ID. We should also remove email if the user disabled notifications. Probably we may store it on the client side to be friendly and not to make users rentering email every time they turn it on/off.

**Comment by umputun** [comment]
If anyone wants to deal with this -  let me know. This is not a trivial enhancement and we better to discuss it first.

**Comment by paskal** [comment]
I'll try to do this one.

**Comment by bronislav** [comment]
I'd like to work on it as well.
