### ISSUE TITLE
Add "contradiction index" metric

### ISSUE THREAD

**Issue by stepagrus** [umputun/remark#274]
Already we have one metric: difference between "voted for" and "voted against".

It would be interesting to have another metric: "contradiction index".

The calculation formula may be as follows:

`difference = abs( voted_for - voted_against )`
`contradiction_index = ( voted_for + voted_against ) /  ( difference == 0 ? 0.1 : difference )`

**Comment by umputun** [comment]
I have added a new field `controversy` to the `Comment` struct and `controversy` sorting key for rest `/find`. 

Now we need UI support for this thing. I think all we need is:
- show the value of `controversy` somehow (hover on scores?)
- add a new sorting mode "controversial" to "sort by" dropdown

**Comment by umputun** [comment]
controversy value calculated differently, similar to [Reddit's version](https://github.com/reddit-archive/reddit/blob/master/r2/r2/lib/db/_sorts.pyx#L60)

```go
func (s *DataStore) controversy(ups, downs int) float64 {

	if downs <= 0 || ups <= 0 {
		return 0
	}

	magnitude := ups + downs
	balance := float64(downs) / float64(ups)
	if ups <= downs {
		balance = float64(ups) / float64(downs)
	}
	return math.Pow(float64(magnitude), balance)
}
```

**Comment by vosi** [comment]
https://en.wikipedia.org/wiki/Binomial_proportion_confidence_interval

**Comment by vosi** [comment]
ааа... присмотрелся, вы и так в ту сторону копнули
