### ISSUE TITLE
Publish base docker images' Dockerfiles

### ISSUE THREAD

**Issue by vblazhnov** [umputun/remark#28]
Base docker images at https://github.com/umputun/remark/blob/master/Dockerfile is `umputun/baseimage`, but there are no public Dockerfiles available on https://hub.docker.com/r/umputun/baseimage/.
Can Dockerfiles of base images be published on Docker Hub?

**Comment by umputun** [comment]
yeah, sure. Thx for the reminder – planned to do it but completely forgot

**Comment by umputun** [comment]
done. published https://github.com/umputun/baseimage and switched both stages to public images
