### ISSUE TITLE
Add drag and drop for images

### ISSUE THREAD

**Issue by umputun** [umputun/remark#285]
The goal is to allow direct drag-and-drop of pictures in github/gitlab style. On the backend will need a new api for upload and UI side will call it and insert md for the image.

**Comment by umputun** [comment]
the code for the backend in `images` branch and it seems to work. However such protected upload and open download functionality introduce potential abuse vector - the bad guy may upload files and never submit the comment. 

I'm not sure how to fight this or if this even a real problem. If it is I can think of:
- some sort of "garbage collector" queueing all newly submitted images and making sure in the next 5 minutes we have a comment referencing the image
- make image upload two-step transaction and completed on a comment's post. Probably we will have to have some "temporary status" for images until a comment posted.
- allow access to images from remark42 iframe only
- some other way?

**Comment by Reeywhaar** [comment]
Thought of it recently, then found drag'n'drop actually works, but it just pastes image url, so then you have to wrap it in \!\[\]\(%url\)

The easy way, I think, is to store an image as data url while preview, and upload only on sending comment. But its still needs management for case of deleted comment and such.

**Comment by umputun** [comment]
some changes in place:

- image name changed from user-defined file (hash) to UUID
- added a top-level directory for users to allow easy removal of all images on "delete me" request

planned changes:

- make image upload 2-step process with the current `Save` storing pictures in a staging area and comments `Create` moving them to the permanent store. Need a way to get a list of all stored images from the comment.
- Add background removal for images sitting in the staging store for too long (EditDuration)
- rest API for image retrieval should be changed to try both long-term and staging. This is needed to allow preview rendering.
- Add parsing of comment to retrieve the list of images 
- Add `Remove` method for images

open question(s):

- not sure yet how to handle image removal from the long-term storage. For example, If comment edited and some links to images removed. Probably the second step should be delayed, i.e. Create call will move comments after EditDuration expired.

**Comment by umputun** [comment]
backend part in place
