### ISSUE TITLE
Comments not loading

### ISSUE THREAD

**Issue by leem32** [umputun/remark#289]
OS: CentOS 7 (on a remote server)
Nginx server

I've closely followed the docs and installed remark42 using Docker. I've also added the frontend script but I get a 404 in the console and can't figure out what I've done wrong. 

My docker-compose.yml:
```
version: '2'

services:
    remark:
        build: .
        image: umputun/remark42:latest
        container_name: "remark42"
        hostname: "remark42"
        restart: always

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"
        environment:
            - REMARK_URL=https://mywebsite.com
            - SECRET=mypassword
            - SITE=di-staging
            - STORE_BOLT_PATH=/srv/var/db
            - BACKUP_PATH=/srv/var/backup
            - DEBUG=true
            - AUTH_GOOGLE_CID=225211674042-13456d6.apps.googleusercontent.com
            - AUTH_GOOGLE_CSEC=pDA1123456
            - AUTH_GITHUB_CID=25c0123456
            - AUTH_GITHUB_CSEC=b17c0a09c0d82f0accee2339123456
            - AUTH_FACEBOOK_CID=2157123456
            - AUTH_FACEBOOK_CSEC=2a9d3772583d6123456

            - AUTH_ANON=true
            # - ADMIN_PASSWD=
        volumes:
            - ./var:/srv/var
```

After I run the command `docker-compose pull && docker-compose up -d`  I get:
```
Pulling remark ... done  
Creating network "remark_default" with the default drive  
Creating remark42 ... done
```

When I run `docker ps` I get:
```                                                                                                                
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                             PORTS               NAMES      
9f4f49d8d104        umputun/remark42:latest   "/entrypoint.sh serv…"   33 seconds ago      Up 28 seconds (health: starting)   8080/tcp            remark42
```

When I run `docker logs 9f4f49d8d104` i get:

```                                                                                                       
    prepare environment
    start remark42 server                                                                                                                       
    remark42 v.1.2.1-440beb3-20190126-01:29:55
    2019/03/17 13:48:47.815 [INFO]  {cmd/server.go:167} start server on port 8080                                                                                
    2019/03/17 13:48:47.815 [INFO]  {cmd/server.go:202} root url=https://mywebsite.com                                                               
    2019/03/17 13:48:47.815 [INFO]  {cmd/server.go:354} make data store, type=bolt                                                                               
    2019/03/17 13:48:47.815 [INFO]  {engine/bolt_accessor.go:52} bolt store for sites [{FileName:/srv/var/db/di-staging.db SiteID:di-staging}], options {Timeout :30s NoGrowSync:false ReadOnly:false MmapFlags:0 InitialMmapSize:0}                                                                                          
    2019/03/17 13:48:47.817 [INFO]  {cmd/server.go:405} make admin store, type=shared                                                                            
    2019/03/17 13:48:47.818 [DEBUG] {admin/admin.go:34} admin users [], email admin@https://mywebsite.com                                                           
    2019/03/17 13:48:47.818 [INFO]  {cmd/server.go:428} make cache, type=mem                                                                                     
    2019/03/17 13:48:47.818 [INFO]  {cmd/server.go:380} make avatar store, type=fs                                                                              
    2019/03/17 13:48:47.818 [INFO]  {provider/providers.go:18} init oauth2 service google                                                                        
    2019/03/17 13:48:47.818 [DEBUG] {provider/providers.go:18} created google oauth2,
      id=225211674042-nm10508fl1mg123456.apps.googleusercontent.co m, redir={https://accounts.google.com/o/oauth2/auth https://accounts.google.com/o/oauth2/token}, endpoint=https://mywebsite.com/auth/google/callback    
    2019/03/17 13:48:47.818 [INFO]  {provider/providers.go:41} init oauth2 service github                                                                        
    2019/03/17 13:48:47.818 [DEBUG] {provider/providers.go:41} created github oauth2, id=251234566, redir={https://github.com/login/oauth/authorize h ttps://github.com/login/oauth/access_token}, endpoint=https://mywebsite.com/auth/github/callback                                                        
    2019/03/17 13:48:47.818 [INFO]  {provider/providers.go:76} init oauth2 service facebook                                                                      
    2019/03/17 13:48:47.818 [DEBUG] {provider/providers.go:76} created facebook oauth2, id=21512345614343, redir={https://www.facebook.com/dialog/oauth https: //graph.facebook.com/oauth/access_token}, endpoint=https://mywebsite.com/auth/facebook/callback                                                         
    2019/03/17 13:48:47.818 [INFO]  {cmd/server.go:484} make notify, type=none                                                                                   
    2019/03/17 13:48:47.818 [INFO]  {api/rest.go:79} activate http rest server on port 8080                                                                      
    2019/03/17 13:48:47.818 [INFO]  {migrator/backup.go:28} activate auto-backup for di-staging under /srv/var/backup, duration 24h0m0s                          
    2019/03/17 13:48:47.818 [DEBUG] {migrator/backup.go:30} first backup for di-staging at 2019-03-18 13:48:47.81854669 -0500 CDT m=+86400.010583659   
    2019/03/17 13:48:47.818 [DEBUG] {api/rest.go:295} no embedded assets loaded, statik/fs: no zip data registered                                               
    2019/03/17 13:48:47.818 [INFO]  {api/rest.go:296} run file server for ./web, path /web
```

Then I add the frontend script in a file called: `remark-comments.php`, just before the closing `body` tag.

```javascript
<div id="remark42"></div>

<script>

  var remark_config = {
    site_id: 'di-staging',
    url: 'https://mywebsite.com/remark-comments.php', // optional param; if it isn't defined window.location.href will be used
    max_shown_comments: 10, // optional param; if it isn't defined default value (15) will be used
    theme: 'dark', // optional param; if it isn't defined default value ('light') will be used
    page_title: 'Hello world' // optional param; if it isn't defined `document.title` will be used
  };

  (function() {
    var d = document, s = d.createElement('script');
    s.src = '/web/embed.js'; // prepends this address with domain where remark42 is placed
    (d.head || d.body).appendChild(s);
  })();

</script>

```

Then I load the `remark-comments.php` page in the browser and I just get a `404` error in the console. The `404` is for the page `https://mywebsite.com/web/embed.js`.

Hopefully I'm missing something obvious, but I can't see it.

Thanks

**Comment by umputun** [comment]
It looks like you are trying to access remark42 with your site url and missing the part described in this line:

```
 s.src = '/web/embed.js'; // prepends this address with domain where remark42 is placed
    (d.head || d.body).appendChild(s);
```

you should have here smth like `s.src=https://remark42.mywebsite.com/embed.js`

Server configuration, i.e. `- REMARK_URL=https://mywebsite.com` should be also pointing to remark's base url, not your web site base url.

@Reeywhaar @Guria @igoradamenko - the setup of UI integration can be a little bit confusing. Can we simplify it and just add `remark_url` in var section the same way it is done for site_id and page_title ?

**Comment by leem32** [comment]
Does the `remark42` in `s.src=https://remark42.mywebsite.com/embed.js` need to match the `hostname` variable in `docker-compose.yml`?

I'm not sure what remarks base url should be. Would it be `https://remark42.mywebsite.com` or `https://remark42.mywebsite.com:8080` maybe?

**Comment by Reeywhaar** [comment]
@leem32 you can test server by opening `https://%domain%/api/v1/config`, if it's live, then script url will be `https://%domain%/web/embed.js`, note the `/web/` part.

@umputun as for script loading, I thought of idea, to split scripts to `vendor.js` and some current script `embed.js` or `counter.js`. This can help with loading time and bundle size, so `vendors.js` can be shared and cached across multiple widgets: `counter`, `last comments` etc... And so we can provide a new loader which looks like so:

```js
var remark_config = {
  host: %REMARK_HOST%,
  site_id: %YOUR_SITE_ID%,
  url: %PAGE_URL%, // optional param; if it isn't defined window.location.href will be used
  max_shown_comments: 10, // optional param; if it isn't defined default value (15) will be used
  theme: 'dark', // optional param; if it isn't defined default value ('light') will be used
  page_title: 'Moving to Remark42' // optional param; if it isn't defined `document.title` will be used
};

(function(d){
  for(script of ["vendors.js","embed.js"]){
    var n=d.createElement("script");
    n.src=remark_config.host+"/web/"+script;
    (d.head||d.body).appendChild(n)
  }
})(document);
```

**Comment by leem32** [comment]
Now I'm even more confused. umputun removed `web` from the script url e.g `https://remark42.mywebsite.com/embed.js`, but you've added it back in.

If my website is called `mywebsite.com` exactly what should be my `script src` e.g `s.src = `?
And also with the same website name exactly what should my `REMARK_URL` be?

I haven't tested this yet but at the moment I have:
`REMARK_URL=https://remark42.mywebsite.com`
and
`s.src = 'https://remark42.leemtestserver.com/embed.js';`

Are those paths correct?

Sorry for asking for the clarification but it just doesn't seem clear to me.

**Comment by Reeywhaar** [comment]
@umputun mistyped it :-), `/web/` should be present.

Have you configured server (DNS, proxy, etc) to work with "https://**remark42**.leemtestserver.com"? You should understand that remark's hostname is not some magic string, and must be configured first and in fact can be anything, for example it can be "https://**comments**.leemtestserver.com", it's your choice.

My suggestion is to sort things by answering some questions:
* First, do you have any variant of %domain% so `https://%domain%/web/embed.js` shows something in browser? For example take a look at https://remark42.radio-t.com/web/embed.js
* Do you run remark via [docker](https://github.com/umputun/remark#with-docker) or with [binary](https://github.com/umputun/remark#without-docker)?
* Do you run remark directly pointing to web, or behind some proxy server, like `nginx`?

Frontend configuration, like what should be `src`, can be solved after server things sorted out.

**Comment by Reeywhaar** [comment]
My guess, you can change REMARK_URL in your `docker-compose.yml` to be `REMARK_URL=http://127.0.0.1:8080` which will bind remark to run locally on server, not pointing to web.

Then you can add proxy pass configuration to nginx, you can check out [nginx-proxy-example.conf](https://github.com/umputun/remark/blob/master/backend/nginx-proxy-example.conf), there you should change `server_name demo.remark42.com;` to `server_name remark42.leemtestserver.com;` or what you have preferred. Also you should change `proxy_pass http://remark42:8080/;` on bottom to `proxy_pass http://127.0.0.1:8080/;`. By that all requests to `remark42.leemtestserver.com` will be proxied to `127.0.0.1:8080`, then you should restart nginx, remark, and check out `https://remark42.leemtestserver.com/web/embed.js'`, note that I haven't touched `SSL_CERT` and `ssl|https` aspect as this is different matter.

I am myself become confused, what purpose `REMARK_URL` does have @__@

**Comment by leem32** [comment]
@Reeywhaar I have followed your last comment, but now when I try to load `https://comments.leemtestserver.com/web/embed.js` I get an `502 Bad Gateway` error :)

I had no problem setting up the SSL because I already use Letsencrypt on my server.
My remark url is `- REMARK_URL=http://127.0.0.1:8080`

My Nginx.conf
```nginx
  server {
    listen 443 ssl http2;
    server_name comments.leemtestserver.com;;

    # nginx: [warn] the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /etc/nginx/nginx.conf
    # ssl    on;

    ssl_certificate      /etc/letsencrypt/live/leemtestserver.com/fullchain.pem;
    ssl_certificate_key  /etc/letsencrypt/live/leemtestserver.com/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/leemtestserver.com/fullchain.pem;

    add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";

    # nginx: [emerg] zero size shared memory zone "perip"
    # limit_conn perip 10;

    location / {

        #CORS
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, PUT, POST, DELETE, OPTIONS';
        add_header Access-Control-Allow-Headers "Content-Type, Authorization, X-Requested-With";

        if ($request_method = 'OPTIONS') {
             add_header 'Access-Control-Allow-Origin' '*';
             add_header 'Access-Control-Allow-Methods' 'GET, PUT, POST, DELETE, OPTIONS';
             add_header 'Access-Control-Max-Age'        86400;
             add_header 'Access-Control-Allow-Credentials' 'true';
             add_header 'Access-Control-Allow-Headers' 'Authorization,DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
             add_header 'Content-Length' 0;
             add_header 'Content-Type' 'text/plain; charset=UTF-8';
             return 204;
         }

         proxy_redirect           off;
         proxy_set_header        X-Real-IP $remote_addr;
         proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header        Host $http_host;
         proxy_pass                http://127.0.0.1:8080/;
     }
}
```

**Comment by Reeywhaar** [comment]
`502` means that proxied server (which is remark in our case) is not running. Sure that remark is running?

In your case I'd ssh into server and check via curl `curl -v http://127.0.0.1:8080/`.

I don't see `ports` exposing section in `docker-compose.yml`, check out https://github.com/umputun/remark/blob/master/compose-dev-frontend.yml, in your case it then should be
```
ports:
 - "8080"
```

**Comment by leem32** [comment]
I've added the port to `docker-compose.yml`:
```yaml
  ports:
   - "8080"
```

And when I run `docker ps` I get:
 ```                             
 CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                   PORTS                      NAMES  
 8ed0839cf162        umputun/remark42:latest   "/entrypoint.sh serv…"   2 minutes ago       Up 2 minutes (healthy)   0.0.0.0:32768->8080/tcp    remark42
```

If I `ssh` into the server and run `curl -v http://127.0.0.1:8080/` I get:
(I also get the same result for `http://leemtestserver.com:8080/`)
```
* About to connect() to 127.0.0.1 port 8080 (#0)
*   Trying 127.0.0.1...
* Connection refused
* Failed connect to 127.0.0.1:8080; Connection refused
* Closing connection 0
curl: (7) Failed connect to 127.0.0.1:8080; Connection refused
```

Shouldn't the port be:
```yaml
  ports:
   - "8080:8080"
```

**Comment by Reeywhaar** [comment]
Do you restart docker services after editing yml by doing `docker-compose down && docker-compose up -d`? Now it's clear that service is either not running or there is misconfiguration. You can start service as non-daemonized by typing in ssh `docker-compose up` and watch for logs

**Comment by leem32** [comment]
I've changes the port to `8080:8080` and when I load the page I get `404 page not found`.

EDIT: Hold on I think it's working now although I get a 404 on the above URL if I navigate to `https://comments.leemtestserver.com/web/embed.js` I get the remark script.

If I navigate to `https://comments.leemtestserver.com/web` it takes me to a page titled `demo page`.

Curling the above URL's also works.

**Comment by Reeywhaar** [comment]
Yep, now everything seems ok. Now you can try to setup frontend

```html
<script>

  var remark_config = {
    site_id: 'di-staging',
    max_shown_comments: 10, // optional param; if it isn't defined default value (15) will be used
    theme: 'dark', // optional param; if it isn't defined default value ('light') will be used
    page_title: 'Hello world' // optional param; if it isn't defined `document.title` will be used
  };

  (function() {
    var d = document, s = d.createElement('script');
    s.src = 'https://comments.leemtestserver.com/web/embed.js'; // prepends this address with domain where remark42 is placed
    (d.head || d.body).appendChild(s);
  })();

</script>
```

**Comment by leem32** [comment]
Hmm When I load the webpage with the above script in your last post the page hangs up for a while and then where the comments would be it says `The connection was reset.`. 
Looking in the dom I can see the remark `iframe` and all accompanied `html` and `css` and the `embed.js` script also has a `200`response code.

**Comment by Reeywhaar** [comment]
You can try to open iframe directly https://comments.leemtestserver.com/web/iframe.html?site_id=di-staging&url=someurl, whoa, leemtestserver is actual server :D, and I see that everything is running. Connection reset may be caused by some browser settings :/

**Comment by leem32** [comment]
The server is just a staging server so is behind an `auth_basic` in nginx. I've tried to load the page in incognito mode in Chrome too but I have the same problem.

**Comment by Reeywhaar** [comment]
Maybe some extension in chrome causes it?

**Comment by leem32** [comment]
Incognito mode disables extensions.

**Comment by leem32** [comment]
The console message I receive after the page fails to load the comments may be the problem e.g
`Error: Cannot set user agent for iframe with location different to this page`

**Comment by Reeywhaar** [comment]
Oh, I see, try to set REMARK_URL to `https://comments.leemtestserver.com/`

**Comment by umputun** [comment]
> try to set REMARK_URL to https://comments.leemtestserver.com/

actually, it should be without trailing "/", i.e. https://comments.leemtestserver.com

**Comment by leem32** [comment]
After changing the `REMARK_URL` to https://comments.leemtestserver.com, comments are now loading :).
I notice there is a `401` for the URL `https://comments.leemtestserver.com/api/v1/user?site=di-staging` is that normal.

Everything looks to be working now though. I've logged in with Github and posted and deleted a comment without any issues.

**Comment by Reeywhaar** [comment]
Yep, 401 is response for not authorized user (guest). Glad that everything works!

**Comment by leem32** [comment]
Thanks for your help :)
