### ISSUE TITLE
Adding backend main domain instead of subdomain

### ISSUE THREAD

**Issue by leem32** [umputun/remark#290]
Just wondering if there's any reason why adding the backend to the main domain e.g `https://example.com/remark42` would not work?

So, this would be instead of using a subdomain for the backend e.g `https://remark42.example.com`.

The nginx.conf would then look something like:
```nginx
  location /remark42/ {
    rewrite /remark42/(.*) /$1 break;
    proxy_pass http://127.0.0.1::8080/;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
```

Doing it this way would make it easier for me to set up the self-signed certificates on my Vagrant VM.

**Comment by umputun** [comment]
> Just wondering if there's any reason why adding the backend to the main domain e.g https://example.com/remark42 would not work?

I don't see a reason. Never tried like this, but should be working

**Comment by leem32** [comment]
I can confirm this does indeed work.

To configure it you just have to set the remark url like: 
`REMARK_URL=https://example.com/comments`

And the nginx config:

```nginx

  location /comments/ {
    rewrite /comments/(.*) /$1 break;
    proxy_pass http://example.com:8080/;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
```

The frontend URL looks like this:
`    s.src = 'https://example.com/comments/web/embed.js;
`

And you also need to slightly modify the callback URL for the social media login API's.

Facebook Valid OAuth Redirect URIs:
`https://example.com/comments/auth/facebook/callback`

Google Authorized redirect URIs:
` https://example.com/comments/auth/google/callback`

Github Authorised callback URL:
`https://example.com/comments/auth/github/callback`

**Comment by umputun** [comment]
I have added this info to [wiki](https://github.com/umputun/remark/wiki/How-to-configure-remark42-without-a-subdomain)
