### ISSUE TITLE
Allow admin users to delete comments through the last comments widget.

### ISSUE THREAD

**Issue by leem32** [umputun/remark#293]
I want to create an admin page where I can quickly scan through the latest posted comments and have the ability to delete them if needed.

I can use the latest comments widget to see the most recent comments but the only way I can delete an undesirable comment is by manually visiting the page and deleting the comment as an admin user.

If I had the same power to do this using the last comments widget it would help speed up the process of deleting comments on sites that have the remark comments engine on multiple pages.

**Comment by umputun** [comment]
Not sure I get it. Do you want to create admin page? If so, PRs are welcome and API supporting it already in place. Or you asking for some delete functionality as a part of recent comments widget? If so, I don't think this widget is the right place for such admin actions.

_Generally speaking, admin panel/dashboard is nice to have_

**Comment by leem32** [comment]
"Or you asking for some delete functionality as a part of recent comments widget?"

Yes, that's what I meant. The delete functionality wouldn't have to come from the recent comments widget though. That was just an idea.

I just think it would be great to have the ability to moderate comments, but after the comments have been posted. So, I could visit the moderation page; view all the recently posted comments across my site and delete the comments I don't like for whatever reason.

If I have remark comments on hundreds or even thousands of pages it would be nice to be able to manage those comments from one place.
