### ISSUE TITLE
cors error when attempting to connect with Authorization API 

### ISSUE THREAD

**Issue by leem32** [umputun/remark#294]
I need to log in using the Authorization API so I can access the `Admin` API, but I'm running into an `Cross-Origin Read Blocking (CORB) blocked cross-origin response` issue.

I've set the nginx headers and also tried to add the same headers in the `Fetch` request.

I'm working on a Vagrant VM. 
Any idea how to get around this?

`nginx headers`
```nginx
    #CORS
    add_header 'Access-Control-Allow-Origin' '*';
    add_header 'Access-Control-Allow-Methods' 'GET, PUT, POST, DELETE, OPTIONS';
    add_header Access-Control-Allow-Headers "Content-Type, Authorization, X-Requested-With";
    if ($request_method = 'OPTIONS') {
         add_header 'Access-Control-Allow-Origin' '*';
         add_header 'Access-Control-Allow-Methods' 'GET, PUT, POST, DELETE, OPTIONS';
         add_header 'Access-Control-Max-Age'        86400;
         add_header 'Access-Control-Allow-Credentials' 'true';
         add_header 'Access-Control-Allow-Headers' 'Authorization,DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
         add_header 'Content-Length' 0;
         add_header 'Content-Type' 'text/plain; charset=UTF-8';
         return 204;
    }
```

`Fetch request`
```javascript
const loginUrl = 'https://dev.example.com/comments/auth/facebook/login?from=https://dev.example.com/recent-comments&site=di-dev&session=1';
const loginParams = {
    headers:{
        "content-type":"application/json; charset=UTF-8",
        // "X-Requested-With":"XMLHttpRequest",
        // headers from remark nginx example
        "Access-Control-Allow-Headers":"Content-Type, Authorization, X-Requested-With",
        "Access-Control-Allow-Methods":"GET, PUT, POST, DELETE, OPTIONS",
        "Access-Control-Allow-Origin":"*",
        "Access-Control-Allow-Credentials":"true",
  },
 method: "GET",
    mode: "no-cors",
};
fetch(loginUrl, loginParams)
  .then(
    function(response) {

      if (response.status !== 200) {
        console.log('Looks like there was a problem. Status Code: ' + response.status);
        return;
      }

      // Examine the text in the response
      response.json().then(function(data) {
        console.log("Response:");
        console.log(response);
 });
 } 
)
  .catch(function(err) {
    console.log('Fetch Error :-S', err);
    console.log('Fetch Error message :-S', err.message);
  });

```

**Comment by umputun** [comment]
CORS already [allowed](https://github.com/umputun/remark/blob/master/backend/app/rest/api/rest.go#L171) by the backend, so you don't need to set it on nginx level. Also, not sure why you adding it to your fetch request.

**Comment by leem32** [comment]
Thanks, I've removed the headers in nginx.
"Also, not sure why you adding it to your fetch request."
Adding what to the fetch request, the headers? I was just trying it out to see if it would fix the cors issue.

I still haven't got this working.

**Comment by umputun** [comment]
I'm not sure what exactly is not working. My guess  - you are trying to auth on one domain and run js from another. In this case, the auth/jwt cookie won't be available. Or if you do auth not from the domain defined in oauth2 settings, it will be rejected by oauth2 providers. 

I"m not UI expert, but you can ping @Reeywhaar and ask. Probably he will need more info to answer it.

**Comment by leem32** [comment]
I'm not trying to auth on one domain and run js from another. And the domain is defined in oath2 settings.

I'm working in a local Vagrant dev environment though, but I don't think thats the problem as I can log in using social media through the remark comments UI without any issues. Even if I run the Fetch request on the same page as where I can log in with social media I still get the cors error.

If I remove `no-cors` from the Fetch request the error is:
```
Access to fetch at 'https://www.facebook.com/dialog/oauth?client_id=2157698161114343&redirect_uri=https%3A%2F%2Fdev.example.com%2Fcomments%2Fauth%2Ffacebook%2Fcallback&response_type=code&scope=public_profile&state=1d4aff5d095abab1767fb0f58d519aa674d216cb' (redirected from 'https://dev.example.com/comments/auth/facebook/login? 
   from=https://dev.example.com/recent-comments&site=di-dev&session=1') from origin 'https://dev.example.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs,   
 set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

I'm losing the will to live :(

**Comment by Reeywhaar** [comment]
What is `dev.example.com`

**Comment by leem32** [comment]
`dev.example.com` is a  virtual host e.g `127.0.0.1 dev.example.com` added to the host file. It's not a real domain. but I have added it to each of the social login redirect URI's.

**Comment by umputun** [comment]
There are way too many things you changed from the typical configuration (url instead of subdomain, runs in vm, rewrite of DNS). To make things even more exotic you run docker inside of Vagrant'a VM, which is kind of strange idea.  Some of these changes probably causing some auth issue, but I have no clue what is this.

None of us using the services in the same exotic environment. I'd recommend you to make it as standard as possible, or at least change one thing at a time. Another observation - you don't need social auth with DNS rewrite to test things locally. We have dev mode with non-social login exactly for this.

**Comment by Reeywhaar** [comment]
In addition, you trying to make cors request to `https://dev.example.com/comments/auth/facebook/login?from=https://dev.example.com/recent-comments&site=di-dev&session=1`.

* First, I don't know what `/comments/` path does here. Standard remark url would be `https://dev.example.com/auth/facebook/login?from=https://dev.example.com/recent-comments&site=di-dev&session=1` without `comments`
* Second, you trying to `fetch` this url, but this is not how this works. By oauth protocol, you should open this page in new tab, where authorization window will be present (or if you already authorized see next), then upon authorization you will be redirected to callback url, which is `https://dev.example.com/recent-comments` that is set as `&from=` parameter. Let me not to describe oauth protocol here. You may check how remark handle oauth [here for example](https://github.com/umputun/remark/blob/2a03afddc66760b4af2173285ed1df9c61cd7774/web/app/common/api.ts#L8)

**Comment by leem32** [comment]
@umputun, Yes, I think it's more likely it will work on a remote server which I will test shortly and let you know.
Running a docker container inside a Vagrant VM (with CentOS) isn't that uncommon least I don't think it is. I'm on a windows host so I don't have much choice.
I'll take a look at the dev-mode for non-social login.

@Reeywhaar 
1. The `comments` path is for the path to the backend e.g `https://dev.example.com/comments/web/embed.js` instead of using a subdomain. The callback URL's had to change slightly due to this e.g `https://dev.example.com/comments/auth/google/callback`.
2. " By oauth protocol, you should open this page in new tab, where authorization window will be present" I'm struggling to understand this. Do you have a code example?
If base_url isn't picking up `comments` path I guess thats the problem.
```javascript
`${BASE_URL}/auth/${provider}/login?from=${encodeURIComponent(
        location.origin + location.pathname + '?selfClose'
      )}&site=${siteId}`
```
If thats the case there's no fixing this unless I go back to using a subdomain.

**Comment by Reeywhaar** [comment]
`BASE_URL` is `REMARK_URL` which you set in config. I don't think that remark have problems with working on subpath, though I haven't tested it yet. Anyway, it's better to move to subdomain to narrow the case, as there are just too many variables.

**Comment by leem32** [comment]
OK thanks for your help. I will concede defeat I think and go back to a subdomain.
Just one more question though. How should I perform the Authorization API request? If Fetch/xmlhttprequest is not the right way to do it then how? I'm thinking `Window.open()` is that OK.

**Comment by umputun** [comment]
>  Do you have a code example?

oauth2 is a complicated beast. If you want to understand the flow there are a lot of resources about it on the internet. But basically, this is a multi-step process from a client's point of view:

- client hits  "login url" for a given provider, i.e. `/auth/github/login`
- the server will communicate with a remote provider (github in this case) and may present github's login page
- provider (github) will hit callback url on server (remer42) side too allow/reject access
- the server retrieves information from a provider within allowed scope, things like user name, user id and avatar 
- server set jwt cookie and return authorized code. 
- server redirect to the url passed as a part of the login request

From this point, you have a cookie with token enclosed in, and each request browser sends will include the cookie, so you logged in and can access protected urls.

**Comment by leem32** [comment]
@umputun Thanks for taking the time to explain all that, It is indeed complicated :)

Just tried something on the off chance and added the url inside an anchor tag e.g.
`<a href="https://dev.example.com/comments/auth/facebook/login?from=https://dev.example.com/recent-comments&site=di-dev&session=1">log in</a>`
When I do this it appears to work. Meaning it takes me to the facebook login page and after I click to login it takes me back to `recent-comments`. The URL has a hash and underscore chars in it though. `/recent-comments#_=_`.
Not sure if I am actually logged in though?

**Comment by Reeywhaar** [comment]
You can try to visit `https://dev.example.com/comments/` (or the page where main comment window present) and see if you logged in. You can also take a look in web inspector what you have in cookies, does auth cookie present. Recent comments widget by itself have no indication whether user logged in or not.

**Comment by leem32** [comment]
Clicking the login anchor tag does log me in. The cookie is present and if I add the main comments to the same page it shows `You signed in as lee28 Sign out?`. The user is also an admin and I can see the admin options underneath each comment. 

So, the login anchor does work. The only problem now lol is when I try to delete a comment by clicking an anchor tag i.e `<a href="https://dev.example.com/comments/api/v1/admin/comment/9eefb403-6024-4544-990b-5f451b19752e?site=di-dev&url=https://dev.example.com/recent-comments">Delete comment</a>` it returns a `401 unauthorized` response.

I', logged in as an admin user and the id after `comment` is the correct comment id. The `URL` is the page the comment is on. 
Have I set the delete URL correctly??

I know I said I was going to go back to the sub-domain, but now I can see the login is working it's giving me a little more hope I can get the delete comment working too.

**Comment by Reeywhaar** [comment]
Read [manual](https://github.com/umputun/remark#admin), request should be sent with `DELETE` http method.

**Comment by leem32** [comment]
Doing that using either `Fetch` or `xmlhttprequest` I get a `DELETE https://dev.example.com/comments/api/v1/admin/comment/9eefb403-6024-4544-990b-5f451b19752e?site=di-dev&url=https://dev.example.com/recent-comments net::ERR_SPDY_PROTOCOL_ERROR`

`Fetch`
```javascript
https://dev.example.com/comments/api/v1/admin/comment/9eefb403-6024-4544-990b-5f451b19752e?site=di-dev&url=https://dev.example.com/recent-comments

const deleteCommentParams = {
    headers:{
        "content-type":"application/json;"
    },
    method: 'DELETE',
};
fetch(deleteComment, deleteCommentParams)
```

`xmlhttprequest`
```javascript
xmlhttp.open ("DELETE", "https://dev.example.com/comments/api/v1/admin/comment/9eefb403-6024-4544-990b-5f451b19752e?site=di-dev&url=https://dev.example.com/recent-comments", true);
xmlhttp.setRequestHeader('Content-Type', 'application/json');
```
I think I'm going to skip this functionality for now. I give up.
I think I've taken enough of your time on this issue and I don't wish to take anymore.
Thanks for your patience :)
