### ISSUE TITLE
Error in IE11

### ISSUE THREAD

**Issue by leem32** [umputun/remark#298]
When I load the comments (latest remark master branch ) in IE11 I get an error in the console: 

```
Object doesn't support this action
var i=new Promise(function(t,n){o=r[e]=[t,n]});
File: remark.js, Line: 1, Column: 629
```

The comments just show the loader.

I don't have this problem in any other browser I've tested.

Does remark still support IE11?

I tried using the pollyfill.io `default` pollyfill which contains the `promises` pollyfill, but the error still occurs.

EDIT: If I load remark in IE11 on the demo page at https://remark42.com/demo/ the comments also fail to load and the console show an error:
```
Unhandled promise rejection Error: Loading chunk 5 failed.
(error: https://remark42.com/demo/vendors~polyfills.js)
"Unhandled promise rejection"
[object Error]{description: "Loading chu...", message: "Loading chu...", name: "Error", request: "https://rem...", stack: "Error: Load...", type: "error"}
```

You may already be aware of that error, but I thought I'd mention it as it's also a `promise` error like the error I have in my code.

**Comment by leem32** [comment]
I'm now loading the remark42 backend from a subdomain  for my live server, but now I'm getting a different error in IE11:
```
  | This content cannot be displayed in a frame
  | To help protect the security of information you enter into this website, the publisher of this content does not allow it to be displayed in a frame.
  | What you can try:
  | Open this content in a new window |   | Open this content in a new window
  | Open this content in a new window

```

**Comment by leem32** [comment]
Any plans on getting remark working with IE11, or is that browser not supported anymore?

**Comment by umputun** [comment]
I'm not sure. From one hand it is about 5% of the market, from the over - even MS is saying you shouldn't use IE 11 unless you have a very specific need. Unless the fix is really trivial I'd say nay. @Reeywhaar - what say you?

**Comment by Reeywhaar** [comment]
I'm going to check everything on old ios versions (9.3), as for IE, well I'd be glad to support, I'll see what I can do

**Comment by Reeywhaar** [comment]
@leem, I have tested yesterday and #313 was merged. Can you check please, if there any issues in ie11? I suspect there can be some related to proxying, because ie doesn't work with dev setup, dev server proxied request constantly gets `ECONNRESET`.

**Comment by leem32** [comment]
Sorry for the delay, I was away from computer. I've tested remark in ie11, but are getting the same error.
```javascript
Object doesn't support this action
var i=new Promise(function(t,n){o=r[e]=[t,n]});
File: remark.js, Line: 1, Column: 629
```
To make sure I was using updated remark  I completely removed the remark container and image from Docker and reinstalled the Git repo then ran `docker-compose pull && docker-compose up -d`.

**Comment by leem32** [comment]
Just noticed however the remark demo page is now working with ie11. Maybe I've installed the remark update incorrectly?

**Comment by leem32** [comment]
@Reeywhaar, I'm still getting the `Object doesn't support this action` error.
Here's how the backend looks. 
Any ideas?

```nginx
server {

    listen 443 ssl http2;

    server_name comments.{{ domain_name }};
    ssl_certificate      /etc/letsencrypt/live/{{ domain_name }}/fullchain.pem;
    ssl_certificate_key  /etc/letsencrypt/live/{{ domain_name }}/privkey.pem;
    ssl_session_cache shared:SSL:40m;
    ssl_session_timeout 21h;
    ssl_session_tickets off;
    ssl_buffer_size 4k;

    # Enable server-side protection against BEAST attacks
    ssl_protocols TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384";
ssl_dhparam /etc/ssl/certs/dh4096.pem;
    ssl_ecdh_curve secp521r1:secp384r1;

    # Enable OCSP stapling
    # ref. http://blog.mozilla.org/security/2013/07/29/ocsp-stapling-in-firefox
    ssl_stapling on;
    ssl_stapling_verify on;
    ssl_trusted_certificate /etc/letsencrypt/live/{{ domain_name }}/fullchain.pem;

    resolver 1.1.1.1 1.0.0.1 [2606:4700:4700::1111] [2606:4700:4700::1001] valid=300s; # Cloudflare
    resolver_timeout 5s;

       # ie11 support headers https://github.com/umputun/remark/pull/313#issue-272179992
      add_header Expires "Sun, 01 Jan 2019 00:00:00 GMT";
      add_header Cache-Control "no-store, no-cache, must-revalidate";
      add_header Pragma "no-cache";

      # ref: https://developer.mozilla.org/en-US/docs/Security/HTTP_Strict_Transport_Security
      # add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload always;";
      add_header Strict-Transport-Security "max-age=0; includeSubDomains";

      # See https://securityheaders.io/ for referer-options:
      add_header Referrer-Policy no-referrer-when-downgrade;

      # X-Frame-Options is to prevent from clickJacking attack
      add_header X-Frame-Options SAMEORIGIN;

       #  disable content-type sniffing on some browsers.
      add_header X-Content-Type-Options nosniff;

      # This header enables the Cross-site scripting (XSS) filter
      add_header X-XSS-Protection "1; mode=block";

location / {
         add_header Expires "Sun, 01 Jan 2019 00:00:00 GMT";
         add_header Cache-Control "no-store, no-cache, must-revalidate";
         add_header Pragma "no-cache";

         proxy_redirect          off;
         proxy_set_header        X-Real-IP $remote_addr;
         proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header        Host $http_host;
         # proxy_pass            http://remark42:8080/;
         proxy_pass              http://127.0.0.1:8080/;
     }
  }

```

**Comment by leem32** [comment]
I've fixed this now. The comments are working in ie11. Thanks :)
In case your wondering, the problem was caused by me having the `image` in docker-compose.yml set to `latest` when it needs to be set to `master`.

change `image: umputun/remark42:latest` to `image: umputun/remark42:master`.

**Comment by umputun** [comment]
cool, closing.
