### ISSUE TITLE
Admin lost visual indication

### ISSUE THREAD

**Issue by umputun** [umputun/remark#302]
I think we used to have admin names highlighted somehow. Will be nice to restore it in some way. Probably we could use "verified" badge for this and show admin's "v" with red.

**Comment by Reeywhaar** [comment]
Hm, haven't mentioned it. Should be easy peasy to add. Suggest to add "good first issue"

**Comment by umputun** [comment]
this is what I see on a site with an older version:

<img width="1270" alt="l2ccl-201904-09191035-bjodv" src="https://user-images.githubusercontent.com/535880/55842944-46a4b000-5afb-11e9-9e50-0a85117bfd9f.png">

**Comment by umputun** [comment]
hmm, looks like this bug is different. All user names are blue if the user logged as admin and all grey if not. @Reeywhaar - I think this is some artifact from your massive refactoring.
