### ISSUE TITLE
Resize uploaded images

### ISSUE THREAD

**Issue by umputun** [umputun/remark#309]
Need to resize uploaded image to predefined dimensions.

_related to #285, similar to #78_

**Comment by umputun** [comment]
@Reeywhaar what is the default width for comments section? I need to figure out what resize limit will be by default

**Comment by Reeywhaar** [comment]
You mean, is there a limit for comment width? If so, there isn't, iframe expands to width of its container. However, on https://radio-t.com/p/2019/04/13/podcast-645/#remark42 max width for comment is 759px. I guess 800px is sensible for default.

But for height there is 300px max.
