### ISSUE TITLE
Hard to understand that worst comment has replies.

### ISSUE THREAD

**Issue by Labutin** [umputun/remark#310]
Take a look at the worst comment here: https://radio-t.com/p/2019/04/02/prep-644/#remark42
It is not intuitive to click two times to collapse icon to be able see replies.
I think if replies were hidden automatically good idea to show additional icon/link to show hidden replies/comments.

**Comment by Reeywhaar** [comment]
It's a bug, there should be plus sign, and comment should be collapsed

**Comment by umputun** [comment]
@Reeywhaar is this an unexpected side effect from #281 ?

**Comment by Reeywhaar** [comment]
Yep, I'm already fixed it, pr coming soon
