### ISSUE TITLE
different toolbars

### ISSUE THREAD

**Issue by umputun** [umputun/remark#314]
the one in reply has a few extra pixels on top
<img width="920" alt="s4bot-201904-21040110-ey73s" src="https://user-images.githubusercontent.com/535880/56467878-44d7c800-63ea-11e9-8ea7-dfa089ce6bca.png">

@Reeywhaar - bug?

**Comment by Reeywhaar** [comment]
Yep, there is .comment__input css which wasn't noticed during adding of toolbar

**Comment by umputun** [comment]
pinging @Mavrin
