### ISSUE TITLE
401 (Unauthorized)

### ISSUE THREAD

**Issue by chessl** [umputun/remark#328]
![image](https://user-images.githubusercontent.com/4500005/57811314-e9260380-7737-11e9-8c90-b3da58bfe993.png)

It appears in the console every time when opening the demo page and my site has the same issue. I checked and the site_id matches.

**Comment by umputun** [comment]
I think this is expected. UI is trying to determine if the user logged in or not. @Reeywhaar - pls confirm

**Comment by Reeywhaar** [comment]
Well, error handling should be there, this should be considered log spam.

**Comment by umputun** [comment]
so, smth to address on your side?

**Comment by Reeywhaar** [comment]
yep, it's a minor bug

**Comment by Reeywhaar** [comment]
oh, sorry, I've mistaken this with console.error message, but this is just plain network request log and nothing can be done here, it's browser thing that @umputun have described.

**Comment by umputun** [comment]
is it considered wrong/bad/annoying? Theoretically, we can address it by changing the response of /user call to return json with "status": "unauthorized", however, this feels odd to me because this is exactly what 401 supposes to represent

**Comment by Reeywhaar** [comment]
I think this clearly will be breaking change. Dunno, this kind of error pops on blink/webkit based browsers, why they have chosen to [treat this as an error](https://bugs.webkit.org/show_bug.cgi?id=37215)? In firefox you get this message if you turned on logging xhr requests in console which is not default.

**Comment by chessl** [comment]
Just found out a [StackOverflow post](https://stackoverflow.com/questions/41515732/hide-401-console-error-in-chrome-dev-tools-getting-401-on-fetch-call) addressing the same issue. It certainly is a chrome thing and I guess I'll just have to ignore it. Thank you!
