### ISSUE TITLE
Errors "Unhandled promise rejection" in logs with Ghostry addon

### ISSUE THREAD

**Issue by vblz** [umputun/remark#333]
Should the app supports work with Ghostery? There are repeated the same errors in console while browsing page with remark widget, like https://radio-t.com/online/, using Ghostery.
![изображение](https://user-images.githubusercontent.com/2076171/57949803-e590a900-78fe-11e9-8980-745357dd460f.png)
Error in logs does not affect work of remark. All functions are available and working well.

FF 66.0.5 (64-bit)
Ghostery 8.3.4

**Comment by umputun** [comment]
I don't think it has anything to do with remark42. To me, it looks like a site-specific issue. 

@Reeywhaar - agree?

**Comment by Reeywhaar** [comment]
Ghostery claims that it blocked "/advertising", facebook, twitter, ya.metrika and google.analytics, I don't know how it related to remark, even it works fine as you say. I think if you install Ghostery — be ready for troubles. I can check how it works with Ghostery, but it will be purely enthusiastic move. I think issue can be closed.
