### ISSUE TITLE
Suggestion: RSS feed for comments should show parent comment

### ISSUE THREAD

**Issue by outcoldman** [umputun/remark#339]
Will be good to see the parent for the new commentaries, if the new commentary is a reply.

**Comment by umputun** [comment]
Can you clarify the idea pls? I mean, there are no good places in RSS to keep the parent comment text anywhere, except Description. In this case, each of the descriptions (except for top-level comments) will include parent's text. Is this what you suggesting?

_pls note - currently parent's user name included in the title field, see [rss.go] (https://github.com/umputun/remark/blob/master/backend/app/rest/api/rss.go#L161)_

**Comment by outcoldman** [comment]
Similarly how disqus does it, every RSS feed item should be something similar to

<img width="643" alt="Screen Shot 2019-06-09 at 9 16 41 AM" src="https://user-images.githubusercontent.com/597158/59160794-5ad34200-8a97-11e9-870b-24c6f1d6b1d6.png">

Where if this commentary is a reply to other commentary, show the parent comment as well.
When reading the commentaries over RSS feed, sometimes is hard to get the context.

**Comment by umputun** [comment]
Confused. How the screenshot above related to RSS? The only RSS feed from disqus I was able to locate is a feed of latest user's activity, i.e. `https://disqus.com/<name>/latest.rss`

example of the item:

```
<item>
			<title>
				Re: Еженедельный подкаст от Umputun
			</title>
			<link>
				https://podcast.umputun.com/p/2018/10/08/podcast-410/#comment-4136737496
			</link>
			<description>
				&lt;p&gt;перенос именно на hugo вызван тем, что остальные подкасты с моим участием этот процесс уже прошли и результат удовлетворяет. Поддерживать несколько разных систем я не хочу, да и не вижу весомых причин для такого разнобразия. Кроме того, опыт прошедших миграций на hugo может помочь и в переносе этого сайта.&lt;/p&gt;
			</description>
			<creator xmlns:dc="http://purl.org/dc/elements/1.1/">
				Umputun
			</creator>
			<pubDate>
				Tue, 09 Oct 2018 11:41:46 -0000
			</pubDate>
</item>
```
I don't see any parent comment in any form here. 

As I said above - I get the idea, but I don't think RSS has a good place to include parent text. Do you have any example of any RSS feed doing this?

**Comment by outcoldman** [comment]
@umputun you are thinking about the RSS feed as just a direct export from the DB. I am suggesting, instead of rendering plain commentaries, wrap them in more informative description. For example:

```
<item>
  <title>
    Re: Еженедельный подкаст от Umputun
  </title>
  <link>
    https://podcast.umputun.com/p/2018/10/08/podcast-410/#comment-1
  </link>
  <description>
    <p>
      New comment:
    </p>

    <blockquote>
      comment1
    </blockquote>
  </description>
  <creator xmlns:dc="http://purl.org/dc/elements/1.1/">
    Umputun
  </creator>
  <pubDate>
    Tue, 09 Oct 2018 11:41:46 -0000
  </pubDate>
</item>
<item>
  <title>
    Re: Еженедельный подкаст от Umputun
  </title>
  <link>
    https://podcast.umputun.com/p/2018/10/08/podcast-410/#comment-2
  </link>
  <description>
    <p>
      New Reply:
    </p>
    
    <blockquote>
      comment2
    </blockquote>

    to 

    <blockquote>
      comment1
    </blockquote>
  </description>
  <creator xmlns:dc="http://purl.org/dc/elements/1.1/">
    Umputun
  </creator>
  <pubDate>
    Tue, 09 Oct 2018 11:41:46 -0000
  </pubDate>
</item>
```

The `description` part is not encoded, to give a better look.

**Comment by umputun** [comment]
> you are thinking about the RSS feed as just a direct export from the DB.

Not really. The current implementation already [dealing with parents](https://github.com/umputun/remark/blob/master/backend/app/rest/api/rss.go#L159) to show "user" > "parent user" in the `title` field. Technically, this is almost trivial to populate parent's text, however, my problem is how to compose `description` with two parts in. Your suggestion is to enclose both the original and the parent in `<blockquote>` tag, and I'm not sure if this the right way. For example, `<blockquote>` can be a part of the text. In addition, I think including the full text of the parent is not really needed for context, just a snippet should be ok (the same way remark42 shows snippets for recent activity). 

I also think such an "extended rss" could be an optional request, (i.e. with ?extended=1 or smth like this) and all current rss feeds should continue to produce the same format as they currently do. 

Generally, I have nothing against the idea but don't know how to implement it correctly from RSS point of view. Maybe `<summary>` tag for the parent's snippet will work, not sure. If you have a clever idea and want to try it - PRs are welcome.

**Comment by umputun** [comment]
I have tried to enclose the parent snippet info inside of  `<summary>` but unfortunately the majority of RSS clients don't render it properly. Switched to <blockquote>, seems to work ok

**Comment by dernasherbrezon** [comment]
Oh. This is causing side effects during rendering in telegram (maybe any other non-html friendly clients). I guess RSS format is hardly compatible with hierarchy of comments. Is it possible to fine-tune this? For example:

```
/api/v1/rss/site?site=site-id&mode=light
```

Currently in the RSS:

```
<description>
<p>Test comment</p> <blockquote><p><p>Кстати, интересно, ...
```

In the telegram (via IFTTT retranslator):
![Screen Shot 2019-11-30 at 10 03 27 PM](https://user-images.githubusercontent.com/1614424/69906572-483e2380-13bd-11ea-8dd9-39ca5bcdef2c.png)
