### ISSUE TITLE
Upgrade querystringify to version 2.0.0 or later

### ISSUE THREAD

**Issue by umputun** [umputun/remark#340]
<img width="861" alt="k08q4_20190608_224915 vcgyi" src="https://user-images.githubusercontent.com/535880/59154765-a954f200-8a3f-11e9-8e4b-f6bc73644a3e.png">

re: @Reeywhaar

**Comment by Reeywhaar** [comment]
hm
* ![Screenshot 2019-06-09 at 17 10 20](https://user-images.githubusercontent.com/884649/59159965-7c551d80-8ad9-11e9-9c27-4d1b28a1b47c.png)
* What github is trying to tell here? What version is vulnerable? Somewhere it tells > 2.0.0 somewhere that every < 2.0.0
* `querystringify` is transitive dependency so github's suggestion to upgrade to >2.0.0 is invalid
* `querystringify`, judging by package-lock.json is 2.1.1 — the latest version right now.

Seems very odd o_0

**Comment by umputun** [comment]
hmm, no clue either. And it disappeared by itself from their security alarms for both remark and radio-t-sites. Probably false positive
