### ISSUE TITLE
User is scrolled to the top of iframe on most actions

### ISSUE THREAD

**Issue by denis-chmel** [umputun/remark#342]
Hi guys,

What: Clicking any link or button scrolls user to the top of the iframe.
Where: Chrome and Safari on Desktop Mac, same on iPhone.

(I guess it's a recently added regression, cause it's very disorienting on desktop, painful on mobile)

Steps to reproduce:
1. open a page with many comments https://radio-t.com/p/2019/06/04/prep-653/#comments
2. scroll several screens down and click "Reply" anywhere
Actual: reply form indeed shown, but you're scrolled onto very top, to the top form (not a reply)
3. scroll down to comment where you clicked "Reply" and click "Cancel"
Actual: reply form is closed, but you're scrolled to the very top again

The same happens when click anything: collapse tree icon, expand tree icon, vote up + vote down (this two scrolls up ~50% times). Even the "Show more" button (appears only on mobile) is unexpectedly scrolling user up after loading more comments:
https://www.dropbox.com/s/wf37y7hwmat7yy7/scrollissue.mp4?dl=0

PS. I didn't dig much but it looks like if the frame is fully re-rendered on every sneeze, resetting any scrolling position.

**Comment by umputun** [comment]
@Reeywhaar I can see this issue too, probably some side effect from the refactoring? I also noticed heavy re-render on a minor events, like vote +/-

**Comment by umputun** [comment]
looks like related https://github.com/radio-t/radio-t-site/issues/91

**Comment by Reeywhaar** [comment]
It seems more like an issue of radio-t site than of remark. Guess remark component unmounts and remounts on particular events. Same thing does not happen, for example, on https://news.radio-t.com/post/temy-slushatelei-653

**Comment by umputun** [comment]
good to know. I'll keep it open for now just in case, till we have aq confirmed fix on radio-t site

**Comment by denis-chmel** [comment]
In fact yeah, the issue is not reproducible after removing `#comments` from URL
