### ISSUE TITLE
Image upload api lost picture

### ISSUE THREAD

**Issue by Reeywhaar** [umputun/remark#343]
Not sure if issue is valid, but I noticed, that image uploaded with image upload api is broken here https://radio-t.com/p/2019/06/04/prep-653/#remark42__comment-e559edb0-706e-48a5-82db-52b54fd74c37

**Comment by umputun** [comment]
It was valid, till 133f5fc3f2fb61b95edd342ebf3de61843c6ea6d

**Comment by Reeywhaar** [comment]
Great!
