### ISSUE TITLE
The hidden user appears when change `Sort by` option.

### ISSUE THREAD

**Issue by malamud** [umputun/remark#345]
related to #334
Steps to reproduce:
1. Hide a user.
The user is in settings, comments are not shown - Ok
2. Refresh the page.
The comments are not shown - Ok
3. Change option in Sort by.
The comments from hidden user are shown - wrong behavior.
4. Click on "hide" again.
Nothing happens

**Comment by umputun** [comment]
pinging @Reeywhaar just in case you missed it.

**Comment by umputun** [comment]
@malamud pls confirm the fix and if all good - close this one

**Comment by malamud** [comment]
Fixed  `master-dad51f0-20190616-17:37:55`
