### ISSUE TITLE
Preview is broken

### ISSUE THREAD

**Issue by umputun** [umputun/remark#346]
@Reeywhaar this is smth recent, probably related to hiding functionality

Attempt to preview in UI shows nothing, the log has this:

<img width="1528" alt="86jlp-201906-15125929-tptki" src="https://user-images.githubusercontent.com/535880/59554761-bc028600-8f6d-11e9-8148-80e697f0d2f8.png">

_no error on the server side, good looking 200 response_

**Comment by umputun** [comment]
@Reeywhaar let me know if you don't have time to fix it. I'd rather revert PR to restore preview because it is much more important functionality.

**Comment by umputun** [comment]
related: don't we need a test on the frontend side to catch such regressions?

**Comment by Reeywhaar** [comment]
Probably, I‘ll have time tomorrow’s evening, msk time.
