### ISSUE TITLE
Email auth

### ISSUE THREAD

**Issue by umputun** [umputun/remark#349]
With https://github.com/go-pkgz/auth/issues/23 in place, we can add email authentication sending confirmation token back to the user. 

1. Implement `provider.Sender` for SMTP
1. add UI support (similar to what @Reeywhaar did for https://github.com/go-pkgz/auth/issues/25)
1. add options to activate and configure email auth
1. add SMTP container to compose example

**Comment by umputun** [comment]
I have added backend support for `email` auth provider.  @Reeywhaar - the code is not merged to master but under email branch. To turn it on this [bunch of params](https://github.com/umputun/remark/blob/email/backend/app/cmd/server.go#L79) should be defined, however for testing the only needed one is `Enable` (AUTH_EMAIL_ENABLE = true). It should print to server log/out auth-token the same way as it does for the example app.

**Comment by umputun** [comment]
Deployed to demo, seems to work. Gmail accepted the email, gravatar fetched.

@Reeywhaar - my email template produces an extremely ugly html, can you pls deuglify it a little bit and make more friendly (i.e., easier to select the token for example). This is [the current template](https://github.com/umputun/remark/blob/master/backend/app/cmd/server.go#L523)

**Comment by umputun** [comment]
<img width="676" alt="e6m8r_20190706_184455 w1llp" src="https://user-images.githubusercontent.com/535880/60762114-3890fd80-a01e-11e9-8f1c-28d37282a655.png">

added to radio-t, frame looks strange

**Comment by umputun** [comment]
also some space between inputs will be nice

**Comment by umputun** [comment]
and, maybe, we better show providers as a dropdown ?

**Comment by Reeywhaar** [comment]
Well, something should be done with dropdown positioning but it's not like easy. The whole top panel should be remade to adapt mobile. I guess it's a matter of another issue.
