### ISSUE TITLE
&mdash; not translated

### ISSUE THREAD

**Issue by umputun** [umputun/remark#354]
I think this should be done on UI side, the same way as we currently do for &amp;

example: https://radio-t.com/p/2019/06/25/prep-656/#remark42__comment-adc3b7c6-3e93-43c1-a294-38956e82052a

**Comment by Reeywhaar** [comment]
Problem with this is that server escapes ampersand in html entity and client get response like this `<p>&amp;mdash;</p>`. It double escaped.

**Comment by Reeywhaar** [comment]
So, solution is to replace all `&amp;` with `&` in processed text, but I'd rather do it on server? Maybe there is some pref in blackfriday?

**Comment by umputun** [comment]
this is not blackfriday replacing it, but [bluemonday](https://github.com/microcosm-cc/bluemonday)

> So, solution is to replace all &amp; with & in processed text, but I'd rather do it on server?

I'm not sure what security impact can be if we do this replacement on the server side. For whatever reason every `&` considered unsafe by bluemonday and replaced by `&amp;`

**Comment by Reeywhaar** [comment]
I think it's not the reason of safety, but more of expectation: what if I want to type exactly `&mdash;` but not want it to be escaped...

**Comment by Reeywhaar** [comment]
Why just twitter can't use exact "—" symbol, why entity ¯\\_(ツ)_/¯

**Comment by umputun** [comment]
I have added enforced unescape for a predefined table of matches. So far it has `&amp;mdash;` only, and It doesn't check the contexts, i.e. it will replace such matches even inside of `<pre>` block.  I think it is fine and nobody would expect `&amp;mdash;` displayed as is in any place.

**Comment by umputun** [comment]
works fine
<img width="831" alt="lmj4n_20190630_125318 w1voo" src="https://user-images.githubusercontent.com/535880/60400171-138c1e80-9b36-11e9-9e54-a78a7a5d0211.png">
