### ISSUE TITLE
Custom User integration

### ISSUE THREAD

**Issue by rebootcode** [umputun/remark#363]
Hi,

I want to integrate the user of my website as auto sign-in comment box with their details:

- I was trying to find, where did you insert new user - **can't find it in hurry**
- I was also trying to find session maintained for logged in user - **can't find it either**
- I was also trying to find any query/function ran to get the current logged in user - **can't find that source part either**

I am looking for above help - is it possible to integrate user from my website to `remark` comment system?

**Comment by umputun** [comment]
Hi, 

Remark42 doesn't maintain sessions but uses JWT tokens. It handled by [go-pkgz/auth](https://github.com/go-pkgz/auth), initialized [here](https://github.com/umputun/remark/blob/master/backend/app/cmd/server.go#L604) and wraps all protected calls as a regular middleware, like [this](https://github.com/umputun/remark/blob/master/backend/app/rest/api/rest.go#L260).

The current logged in user extracted from jwt cookie and this token has all info remark42 knows about [the user](https://github.com/umputun/remark/blob/master/backend/app/store/user.go#L17) - id, name, avatar, admin flag, blocked flag and so on. All this info extracted with [rest/user.go](https://github.com/umputun/remark/blob/master/backend/app/rest/user.go) helpers from `http.Request`.
 
There are at least 3 ways to integrate auth into your existing system:
1. implement your own direct provider. Currently, remark42 uses direct provider to allow [anonymous access](https://github.com/umputun/remark/blob/master/backend/app/cmd/server.go#L538).
1. Extend your website login implementation to make remark42 jwt directly and set it as a cookie. 
1. Implement a custom auth, supporting sessions or whatever mechanism your site is using. As long as you provide a custom middleware populating user info into request's context in the same way as current auth does, other parts of remark42 will accept it without any changes. 

hope it helps.

**Comment by rebootcode** [comment]
Can you please explain part 3 - implement a custom auth, supporting sessions.
=> I am already doing this - now, how can I pass it to "remark42"

=> current auth does => I am not sure, how current auth populates user's info on remark42 and set sessions.

Note: I am not using JWT, nor I have any plan to use, I prefer secure and safe cookie method.

**Comment by umputun** [comment]
> Can you please explain part 3 - implement a custom auth, supporting sessions.

implement your own middleware to read from your cookie and populate to request's context. This how  the current [auth does it](https://github.com/go-pkgz/auth/blob/master/middleware/auth.go#L61)

> I am not sure, how current auth populates user's info on remark42 and set sessions.

like [this](https://github.com/go-pkgz/auth/blob/master/middleware/auth.go#L114). In  your case, you will get the info from the cookie instead of jwt. 

this is the actual code adding user info to the request:
```
func SetUserInfo(r *http.Request, user User) *http.Request {
	ctx := r.Context()
	ctx = context.WithValue(ctx, contextKey("user"), user)
	return r.WithContext(ctx)
}
```

note: if you going to share your auth cookie with remark42 make sure they are actually sharable, i.e. remark42 runs on a subdomain, see #294

_3 is the most complicated way. I would recommend the first one._

**Comment by umputun** [comment]
One more thing to clarify the whole picture - generally speaking, you are asking for SSO. Remark42 just embedded as an iframe into your site but it still an external system. For such SSO to work properly your system should be some kind of auth provider for others. This is how we do auth with google/github/fb and others - they are oauth2 providers. If your system/site can act like this it can be painless integration and all it needs is to allow custom oauth2 provider(s) to be defined in `go-pgz/auth` which should be an almost trivial thing to do.

Methods I have described above **require code change on remark42 side** to achieve the same (similar) result. I'm not sure if you are willing to maintain your own fork for this, but based on your questions looks like this is your plan.

**Comment by rebootcode** [comment]
Thank you for your response! I think, I will quite here - remark42 doesn't suit my requirement if it can not connect to my existing system user base. I have started to build my own.

Thanks a lot for your help!

**Comment by saucesaft** [comment]
Hey, what could be done to implement option 1 in my site?

**Comment by paskal** [comment]
@saucesaft the answer is "it depends", I'm afraid if you don't know where to start and can't provide any information about what you want to achieve exactly, there is no way to help you.
The general idea is to look into [devAuth provider](https://github.com/umputun/remark42/blob/master/backend/app/cmd/server.go#L465) and do something similar.

**Comment by akronbook** [comment]
Does remark42 support OAuth2 providers like Keycloak?

**Comment by umputun** [comment]
remark42 support various providers - Google, Twitter, Facebook, Microsoft, GitHub, and Yandex. All of them, except Twitter, are ouath2

**Comment by PureLandFlying** [comment]
Hi @umputun ,

If I implemented keycloak integration, is it possible to merge into this repository?

If yes, I will push my code and send the merge request.

**Comment by umputun** [comment]
Hi,

Yes, it will be very nice. However, all auth-related things were migrated to [go-pkgz/auth](https://github.com/go-pkgz/auth). Probably your PR should go to that library`.

**Comment by PureLandFlying** [comment]
Unfortunately, we are using golang.org/x/oauth2 to connect KeyCloak.

**Comment by umputun** [comment]
Not sure why "unfortunately". In fact, it is even fortunately as go-pkgz/auth implements all other providers on top of golang.org/x/oauth2, see https://github.com/go-pkgz/auth/blob/master/provider/oauth2.go for example

**Comment by PureLandFlying** [comment]
Okay, I will refactor the code when I get free.

Thanks!

**Comment by paskal** [comment]
@PsOsDev my suggestion still stays valid:
> The general idea is to look into [devAuth provider](https://github.com/umputun/remark42/blob/adb77d9/backend/app/cmd/server.go#L586-L594) and do something similar.

**Comment by MarcoGriep88** [comment]
What happend to the keycloak integration? has it been merged?

**Comment by paskal** [comment]
Nobody implemented it. There is no keycloak integration with Remark42.
