### ISSUE TITLE
Add a button for image upload

### ISSUE THREAD

**Issue by umputun** [umputun/remark#371]
Apparently, users have no idea pictures can be dropped into comments. In addition, there is no way to do it on the mobile version. Will be nice to add an image upload button to the toolbar with a hint saying something about drag-and-drop as well.

**Comment by umputun** [comment]
ping @Mavrin

**Comment by Mavrin** [comment]
What do you think about this 
<img width="663" alt="Screen Shot 2019-07-12 at 11 35 02 AM" src="https://user-images.githubusercontent.com/1193817/61114539-31904200-a499-11e9-9b42-547dbe43ffc9.png">

**Comment by umputun** [comment]
I'm not sure why this button has a text label

**Comment by Mavrin** [comment]
Because it not clear, what that icon will do. For example, gitlab and github describe how to upload files.
Of course it is not problem to remove text label

**Comment by umputun** [comment]
well, other buttons are not clear the same way, but the tooltip is enough to figure.

**Comment by umputun** [comment]
@Reeywhaar is cut-and-paste images via clipboard suppose to work? I think it worked once, but can be wrong

**Comment by Reeywhaar** [comment]
No, there is no any code related to this.

**Comment by umputun** [comment]
> No, there is no any code related to this.

Can we add some code related to this? I mean if not a big deal will be nice to support it. To me, such functionality looks exotic, but somehow users expect it to work with the clipboard as well

**Comment by Reeywhaar** [comment]
Yeah, I am myself find this feature good to have. Github has this, so I think it's totally possible.

**Comment by mohammedi-haroune** [comment]
The upload button is still missing from the demo ? is it available for self-hosted installation ?
![remark42](https://user-images.githubusercontent.com/23096288/77619593-d4f68980-6f38-11ea-9259-df23eb6dce9a.png)

**Comment by umputun** [comment]
I can see it on the demo site:

<img width="695" alt="buxvqovxat-20200326-022447" src="https://user-images.githubusercontent.com/535880/77620856-4b7b9300-6f09-11ea-8612-6978bb8c5f67.png">

The only reason I can think of - you logged as anonymous. In this case image upload disabled by design https://github.com/umputun/remark42/blob/master/backend/app/rest/api/rest.go#L320

**Comment by mohammedi-haroune** [comment]
Thank you @umputun for your response.
