### ISSUE TITLE
Optional support for emojis 

### ISSUE THREAD

**Issue by umputun** [umputun/remark#374]
The goal is to integrate emoji syntax like `:smile:`, `:beer:` and so on. 

[EMOJI CHEAT SHEET](https://www.webfx.com/tools/emoji-cheat-sheet/)

**Comment by umputun** [comment]
implemented in dda4f87db283ba37da479519ae19022f17b01726. The new option is `--emoji` and env `$EMOJI`

**Comment by StaroKep** [comment]
@umputun, привет. Думаю заняться этой задачей. 

Это нормально, что на локальной машине не отображаются emoji в комментариях?
https://yadi.sk/i/Ju5zcAjYdb8rNw

Нормально, если при вводе emoji будет появляться выпадающее меню, в котором стрелками можно выбрать необходимый emoji?
