### ISSUE TITLE
Emoji autocomplete

### ISSUE THREAD

**Issue by umputun** [umputun/remark#378]
With #374 users can enter emoji as `:blah:` however we don't help them on UI side. I can expose `emoji_enabled` flag to ` /config` response and it will be nice to support such auto-completion/selection on UI side

**Comment by StaroKep** [comment]
@umputun, привет. Думаю заняться этой задачей. 

Это нормально, что на локальной машине не отображаются emoji в комментариях?
https://yadi.sk/i/Ju5zcAjYdb8rNw

Нормально, если при вводе emoji будет появляться выпадающее меню, в котором стрелками можно выбрать необходимый emoji?

**Comment by umputun** [comment]
_@StaroKep спасибо, что вызвался. Пожалуйста, используй english во всех коммуникациях тут, т.к. не все из участников знают великий-и-могучий._

emoji should be working locally the same way as on demo site. I have tried the master and had no problem with emoji processing/preview. Make sure you update your local repo and build it.

<img width="824" alt="kiwer-201910-02155511-u662a" src="https://user-images.githubusercontent.com/535880/66081215-3232f480-e52d-11e9-994e-1bcdf6da011d.png">

regarding ui - yeah, it should open a selection and user should be able to navigate with mouse or keyboard. This is how rocket.chat does it:

<img width="667" alt="bmc78-201910-02155815-qjkaq" src="https://user-images.githubusercontent.com/535880/66081469-a1a8e400-e52d-11e9-9d35-67bcf2f197bf.png">

**Comment by StaroKep** [comment]
@umputun ok. Thanks for the information! 
Configured the local version for frontend development.
I’ll make a branch and I will implement it in my free time.
