### ISSUE TITLE
Redesign UI rendering for the list of auth providers

### ISSUE THREAD

**Issue by umputun** [umputun/remark#382]
Currently, the number of providers remark42 supports out of the box is 6 (google, github, facebook, yandex, email, anon). It also allows defining multiple direct providers, so the total number in some cases can be up to 10.

The selection line is limited to 3 or 4. This is what it looks like on the demo site:

<img width="716" alt="lxxqs-201907-23114504-99nk4" src="https://user-images.githubusercontent.com/535880/61730925-0383eb00-ad40-11e9-8256-5d2a5fa8554d.png">

and this is selection on one of the real sites:

<img width="738" alt="ukidv-201907-23115026-hj8xy" src="https://user-images.githubusercontent.com/535880/61731000-27dfc780-ad40-11e9-8e8b-3bb2093d85c8.png">

We should figure out how to reorganize this part of UI to allow tens of providers to be listed without making it ugly. I'd suggest showing one by default (the first one) and others under a drop-down "More ways to authenticate" or smth like this. The moment user picked the provider it will become the default choice and will be stored on browser-side (localStore)

**Comment by umputun** [comment]
@Reeywhaar let me know what you think about this idea

**Comment by Reeywhaar** [comment]
Hiding providers in dropdown will result that we have dropdown in dropdown (email for example), and I see a lot of problems with their placement, especially on mobile. I think there should be easier solution.

**Comment by umputun** [comment]
easier solution fine with me as long as it is not limiting us to 4 choices.

**Comment by Reeywhaar** [comment]
Started work at https://github.com/umputun/remark/tree/auth-login-design, right now following your idea as nothing else comes to mind.

**Comment by Reeywhaar** [comment]
Updated https://github.com/umputun/remark/tree/auth-login-design. It's more of working now. It remains to:
* add last logged in provider to localStorage
* place it first
* right now threshold where I start to hide providers behind "other" is 3, so if there 4 providers, then 2 would be right away, and 2 behind "other". I think I can add some logic to take big screens into account and increase threshold
