### ISSUE TITLE
How to login as admin by api

### ISSUE THREAD

**Issue by chan15** [umputun/remark#385]
Excuse me, you mentioned 

> Admin authentication (--admin-password set) allows to hit remark42 API without social login and with admin privileges. Adds basic-auth for username: admin, password: ${ADMIN_PASSWD}.

I already set the admin password, but can't find any way to login in by username `admin` and my `password`, how to do that, thanks a lot.

**Comment by umputun** [comment]
I believe this part is explained in the readme you just quoted:

> Admin authentication (--admin-password set) allows hitting remark42 API without social login and with admin privileges. Adds basic-auth for username: admin, password: ${ADMIN_PASSWD}.

Technically it means you could make authenticated REST calls with basic auth, i.e. `http://admin:password@127.0.0.1:8080/api/v1/find....`

Pls, note - UI doesn't expose a way to login with basic-auth as it is not intended for any use outside of development and testing. README has a direct warning about it - "make sure you don't keep ADMIN_PASSWD=something... for any non-development deployments"/ The only valid use case for admin/password basic auth is to simplify development and testing and allow testing API calls without dealing with JWT headers and/or cookies.

**Comment by BarryRufer** [comment]
- AUTH_GITHUB_CID=12345667890           # oauth2 client ID
            - AUTH_GITHUB_CSEC=abcdefg12345678      # oauth2 client secret
How and where to get it?

**Comment by umputun** [comment]
pls see README file, namely section [Register oauth2 providers/GitHub Auth Provider](https://github.com/umputun/remark#github-auth-provider)

**Comment by BarryRufer** [comment]
Thx, how to install Anonymous Auth Provider?

**Comment by BarryRufer** [comment]
Forbidden

![изображение](https://user-images.githubusercontent.com/57297188/68228523-48394680-fffe-11e9-8c5b-6a5ed64064fc.png)

**Comment by umputun** [comment]
this should be fixed in master as well as on the demo site.

All you need to enable anonymous login is to set `- AUTH_ANON=true` in docker-compose.yml file
