### ISSUE TITLE
API description enhancement

### ISSUE THREAD

**Issue by wuzzapcom** [umputun/remark#386]
Remark API is described in [this](https://github.com/umputun/remark/blob/master/backend/remark.rest) file. 
It looks like some custom syntax that doesn't look well from github's GUI or in editor(no syntax highlighting).
Have you considered using Swagger for this? This will improve readability(since swagger is json/yaml) and provide common and understandable syntax.

**Comment by umputun** [comment]
The file is not the API description, but the input with rest's test cases for IDE/editor supporting such a DSL. I don't expect github to highlight it as this file is not intended to be consumed by people.  Any semi-modern dev. editor supports this syntax. There is [vscode extension](https://marketplace.visualstudio.com/items?itemName=humao.rest-client) and, probably, there is something similar for Atom. All IntelliJ IDEs [support it as well]( https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html).
