### ISSUE TITLE
"Sort by" selector doesn't have any indication on focus

### ISSUE THREAD

**Issue by life777** [umputun/remark#389]
Hi,

Thanks a lot for this awesome project.
I found small issue connected with accessibility. If you navigate around comments with Tab button you'll see that all links and buttons have outline (small blue border) when they are in focus:

![Screenshot from 2019-07-25 16-26-59](https://user-images.githubusercontent.com/891497/61906298-0f66dd00-aef9-11e9-89c6-77623dc4bfe4.png)
and
![Screenshot from 2019-07-25 16-27-57](https://user-images.githubusercontent.com/891497/61906380-33c2b980-aef9-11e9-88b6-a5a76ef89162.png)

But "Sort by" selector doesn't have it but this selector element is focusable. It means when an user presses Tab and focuses on the selector and the user doesn't know where the focus is and what will happen if he/she presses Enter. It looks like there is no focus at all.

Thanks a lot.

**Comment by Reeywhaar** [comment]
Thanks! Should be fixed

**Comment by Reeywhaar** [comment]
@life777 should be fixed with 1.4

Closing for now.
