### ISSUE TITLE
can't see indent line in nest structure

### ISSUE THREAD

**Issue by chan15** [umputun/remark#392]
![image](https://user-images.githubusercontent.com/1229833/61920823-76ce6c80-af8d-11e9-8b19-d5f21a542fde.png)

This is the demo from official website

when the article turns to nest structure we can see the indent line, it will add `thread_indented` class to the div automatically

![image](https://user-images.githubusercontent.com/1229833/61920883-b85f1780-af8d-11e9-8fa4-16ee81bcc6d1.png)

this is the latest version I use with docker, it is gone, I can't even find `thread_indented` in the `remark.css` file, how to make it work?

**Comment by umputun** [comment]
Demo site runs the `:master` version, not the `:latest`. Latest tag mean latest **stable version** (1.3). The change you mentioned will be in the ":latest" as soon as 1.4 released.

In meantime, you can switch you docker-compose to  `umputun/remark42:master`, however, this version is not released yet and may have bugs.

**Comment by chan15** [comment]
thank you so much
