### ISSUE TITLE
Unexpected comment removal on "copy link"

### ISSUE THREAD

**Issue by umputun** [umputun/remark#405]
Run into this **very annoying bug** today (safari on a mac). To reproduce:

1. Start to write a comment, but don't hit submit
1. Scroll page up/down and  copy any link ("Copy Link" with a right button click)
1. See comment's text gone :(

_I suspect it has very little to do with links, but probaly clipboard related_

**Comment by Reeywhaar** [comment]
Oh, it's not related to copy. It's related to fact that comment gets replaced with hollow div if it gets out of view.

**Comment by umputun** [comment]
Was this change (replaced with hollow div) introduced before or after 1.4 release? I'm asking to figure if we need 1.4.1 hotfix or not.

**Comment by Reeywhaar** [comment]
after, it was in #397
