### ISSUE TITLE
A comment thread is not shown 

### ISSUE THREAD

**Issue by kostimoshenko** [umputun/remark#411]
Not sure whether it's an issue of Remark42 or some bug related to how it was installed. Please help if you can. 
I was notified about a new comment via telegram, I opened the link and replied to the comment. Link to the comment: https://konstantin.ist/july-2019/?fbclid=IwAR1sX0aHpIlty0ae_1r105auzMPgGZBlioOupetoOx6Posbm64Kt2euE6Bg#remark42__comment-e1699883-dcb5-46fd-ba0d-e2e63eff49e1

However, if you open the URL of this blog post itself, this comment is not shown: https://konstantin.ist/july-2019/ 

The comments to the other blog posts work just fine though.

**Comment by Reeywhaar** [comment]
Hm, I see no comments either ways. There is no errors there, remark's api returns empty list. Though I see comments for previous post. Can you elaborate a bit, what should I see there? Maybe screenshot?

**Comment by kostimoshenko** [comment]
Thank you for the response. 
Here is what I see if I click on the first link 
![Screen Shot 2019-08-13 at 19 32 00](https://user-images.githubusercontent.com/50583946/62959345-40a04200-be01-11e9-83f0-b945326d82fc.png)

**Comment by umputun** [comment]
I see the first, but not the second. To me, it looks like the issue with URL mismatch as a comment created for URL  https://konstantin.ist/july-2019/?fbclid=IwAR1sX0aHpIlty0ae_1r105auzMPgGZBlioOupetoOx6Posbm64Kt2euE6Bg but a second link (https://konstantin.ist/july-2019/) is a short form of this, without query param

**Comment by kostimoshenko** [comment]
Thank you @umputun. 
I am not a developer, so although I seem to understand what you meant, I can hardly imagine how to: 
a) amend this particular comment so that it shows below the post 
b) prevent this from happening again. Seems like the lady who commented the post found the link on facebook, hence the query parameter in URL. 
Would appreciate if you advised on this.

**Comment by Reeywhaar** [comment]
How do you see comments? I'm have nothing. https://remark.konstantin.ist/api/v1/find?site=konstantin.ist&url=https://konstantin.ist/july-2019/&sort=-active&format=tree returns

```
{"comments":[],"info":{"url":"","count":0,"first_time":"0001-01-01T00:00:00Z","last_time":"0001-01-01T00:00:00Z"}}
```

**Comment by kostimoshenko** [comment]
> How do you see comments? I have nothing. 

Hey @Reeywhaar, not sure whether your question was addressed to me, but seems like @umputun  has already found out where the problem lies (see above). 

Any chance to get fix suggestions?

**Comment by umputun** [comment]
@Reeywhaar - your url param is wrong. You need the full thing, with `fbclid` part, like it is in the first link.

@kostimoshenko - Remark42 (backend) links comment to posts by url passed in. The frontend uses the link of the active window to figure what is the post URL. In this particular case query params seem to play no role in identifying the post, but I can imagine opposite cases. @Reeywhaar - I don't see any generic solution for this issue and the only suggestion I have is to add UI conf/param enforcing use of "naked url", i.e. trimming all query params.

Note: back in days I used disqus I run into a similar issue a couple of times. Their solution was different but confusing - admin UI allowed to change the "matching link"

**Comment by umputun** [comment]
@kostimoshenko - as a quick fix suggestion I could recommend striping url params on your side. I'm not sure what blog engine you use and how pages generated, but most likely you run some reverse proxy (nginx or smth like this) in front and you can add a redirect from {url}/?params to {url}. It will not fix the current comment but will prevent such issues from happening again

**Comment by umputun** [comment]
Unfortunately, there is no built-in editor or API to change the link in the store. We may add such API and UI support someday, but as of now, your best bet is to export remark42 data, edit the link and import. 

You can also try to use some external "boltdb ui/editor" and change the link directly. The post you are looking for in the bucket "posts" and you will need to change both bucket key and edit the value as well.

Probably, you would like to stop remark42 and copy your *.db file before you do any of this.

**Comment by kostimoshenko** [comment]
@umputun, first method worked just fine, thank you for the suggestion. 
And I would also like to separately thank you for a wonderful commenting system. It's really good as it is now, but seems like with all the efforts you keep putting in it, it is definitely destined to become even better
