### ISSUE TITLE
Export to WordPress

### ISSUE THREAD

**Issue by OnlineBiblioTK** [umputun/remark#420]
Is it possible to make export to WordPress?

**Comment by umputun** [comment]
Did you mean export comments from remark42 to wordpress? If so, the answer - sort of/kind of possible, but indirectly. Remark's export file (or backup file) just a list of all comments in json and it should be doable to write a converter to whatever format you need for wordpress. Obviously, such a converter is not a part of remark42.

If you meant import from wordpress - this functionality already exists.

**Comment by OnlineBiblioTK** [comment]
Oh yes, of course, backup file! .. Thanks.
