### ISSUE TITLE
Email authentication produces spammy looking emails

### ISSUE THREAD

**Issue by cooperaj** [umputun/remark#429]
I've just implemented email auth on my system and am having issues with the *outgoing* rspamd instance attaching spam headers to the mail. They're mostly all fixable things and would help the email get through on the users SMTP instance.

![Screenshot 2019-09-05 13 56 58](https://user-images.githubusercontent.com/400210/64343786-121f1c80-cfe5-11e9-8ca0-01a60f5a3b23.png)

[MISSING_MID] which is a "missing message id"
[R_BAD_CTE_7BIT] which is "bad content-transfer-encoding"
[CT_EXTRA_SEMI] is because the content-types ends with a semicolon
[MISSING_DATE] is because the message is missing a date
[MIME_HTML_ONLY] is because the message is html only and does not contain a plain text part.

I'm ignoring the url in subject one as thats on me and easily changed :P

**Comment by umputun** [comment]
email auth handled by a separate library [go-pkgz/auth](https://github.com/go-pkgz/auth)

**Comment by umputun** [comment]
I have fixed "ends with a semicolon" issue, added a date header as well as content-transfer-encoding (quoted-printable). The change is not merged into remark42 yet, but eventually, it will be in.

However, this won't be enough to prevent from spam detection in the modern world. I'd suggest using some third-party service providing send functionality, for example [mailgun](https://www.mailgun.com). I use it on all of my sites, and it makes good-looking emails with the proper DKIM, SPF, and everything else needed to pass anti-spam filters.

**Comment by umputun** [comment]
Merged to master. Give it a try to see if it made rspamd happier

**Comment by umputun** [comment]
@cooperaj did it help?

**Comment by cooperaj** [comment]
Sorry, not had the opportunity to give it a go yet. Will try in the next day or so.

**Comment by paskal** [comment]
@cooperaj have you had a chance to look into it? I'm working on comment replies email notifications and I am wondering if changes @umputun made made things better for you.

**Comment by umputun** [comment]
pinging @cooperaj

**Comment by umputun** [comment]
Closing this one. @cooperaj - if you still have the issue pls reopen
