### ISSUE TITLE
Using Github Actions

### ISSUE THREAD

**Issue by Smolevich** [umputun/remark#433]
Do you have plans use Github Actions as CI or it's too early to talk about it?
[Docs](https://help.github.com/en/categories/automating-your-workflow-with-github-actions)

**Comment by umputun** [comment]
I'm experimenting with Actions in some smaller projects and don't have anything against it. It is not polished yet but seems to work. However, as of now, there is no good reason to force the transition (travis works ok for pubic builds, drone does the decent job for deployment), so I will deal with this someday, maybe.

If you want to deal with the transition from travis feel free to submit a PR.

**Comment by Smolevich** [comment]
I didn't find where these [variables](https://github.com/umputun/remark/blob/master/Dockerfile#L5-L14) are used in build image. Are they used implicitly somewhere?

**Comment by Smolevich** [comment]
I prepared PR https://github.com/umputun/remark/pull/434

**Comment by Smolevich** [comment]
Official action from coveralls https://github.com/marketplace/actions/coveralls-github-action

**Comment by Smolevich** [comment]
@umputun, do you have plans to use Github Package Registry in ci ?

**Comment by umputun** [comment]
Last time I checked actions, it had a nasty and very unexpected issue - packages were implicitly linked to releases and each push to github's docker registry made another release. I have reported the issue to them and they promised to fix it:

> We're currently investigating how we might untangle releases and tags from packages so that they are fully independent of one another, it's something we are hoping to address really soon and I've added a +1 against this for you. Hopefully in future creating a package, and publishing a version won't create a release/tag.

Regardles the packages problem I don't see the reason for switching from docker hub to github's registry. This is the only part of packages I can think about relevant to the project.

**Comment by Smolevich** [comment]
Ok, i understand.
Maybe use `docker pull` from Docker Hub before `docker build` in Github Actions ci and then use `cache-from` for using caching image layers. It can help to decrease time build stage

**Comment by umputun** [comment]
I have switched completely to actions, thank you @Smolevich 

The issue with overalls caused by different build number logic and some missing env vars. This all seems to be fine now
