### ISSUE TITLE
"bolt" image storage type isn't supported

### ISSUE THREAD

**Issue by smaant** [umputun/remark#445]
[Readme](https://github.com/umputun/remark/blob/master/README.md#parameters) and [source code](https://github.com/umputun/remark/blob/master/backend/app/cmd/server.go#L121) mention `bolt` image storage type. But looks like it isn't supported atm (https://github.com/umputun/remark/blob/master/backend/app/cmd/server.go#L485).

**Comment by umputun** [comment]
yeah, looks like I never implemented this storage for images. Should be easy to do, I'll mark it as "good-first-issue" and hopefully, someone will help with this.

**Comment by mdjhd** [comment]
Would like to give it a try

**Comment by mdjhd** [comment]
First time trying to contribute to open source, any remarks and suggestions are very much appreciated

**Comment by Vdimir** [comment]
I'll try to implement.  I'll notify if I give up in few days.

**Comment by smaant** [comment]
oops, didn't see that ^ PR and just submitted mine https://github.com/umputun/remark/pull/450
