### ISSUE TITLE
Version info missing from non-docker binaries

### ISSUE THREAD

**Issue by seqizz** [umputun/remark#456]
Sorry if given somewhere else, but I think app could benefit showing the version number somehow.. :slightly_smiling_face:

**Comment by umputun** [comment]
the application already prints the version without any spacial flag, i.e.:

```
docker run -it umputun/remark42 server -h

prepare environment
start remark42 server
remark42 v1.4.0-7fd3c56-20190728-12:44:20
Usage:
  remark42 [OPTIONS] server [server-OPTIONS]
```

In this case, `v1.4.0-7fd3c56-20190728-12:44:20` is the version number, part of commit hash, and build time-stamp.

**Comment by seqizz** [comment]
Hmm, weird. I am running remark as systemd service (which also triggers via `remark server` only) and no version information hit the logs. server -h output also only shows the name of the binary here ($0):

```
~ ⚡> /var/www/remark/remark server -h | head
remark42 local
Usage:
  remark [OPTIONS] server [server-OPTIONS]

Application Options:
      --url=                            url to remark [$REMARK_URL]
      --secret=                         shared secret key [$SECRET]
      --dbg                             debug mode [$DEBUG]

Help Options:
...
```

Anyway, currently I'm using with renaming to append the version number and symlinking afterwards :)

```
⚡> file /var/www/remark/remark
/var/www/remark/remark: symbolic link to `/var/www/remark/remark42.linux-amd64-1.4.0'
```

**Comment by umputun** [comment]
in this "remark42 local" local is the version. Looks like I've never populated version info into non-docker version
