### ISSUE TITLE
customizin docker-compose.yml with few questions

### ISSUE THREAD

**Issue by joseph-vidal-rosset** [umputun/remark#460]
I am not very familiar with docker installation and I still need some help. Following your good documentation, I just succeeded to fill what concerns social medias in docker-compose.yml . Now I wonder about the best folder to put docker-compose.yml in order to run the command docker-compose pull && docker-compose up -d  . In /etc/docker/ ? In /var/html/vidal-rosset.net i.e. the folder of my website? Second and last question: I wonder also if I have to change the volumes:
            - ./var:/srv/var  at the end of the docker-compose.yml file, because the path of my website is /var/www/html/vidal-rosset.net/   Every information to succeed this docker install will be welcome. 
Again and in advance, many thanks for your very kind help.

**Comment by umputun** [comment]
> Now I wonder about the best folder to put docker-compose.yml 

This can be any place on your server, for instance `/srv/remark42` or `/opt/remark42`.  This is **not** `/etc/docker`. Note: you need full read-write permission for this folder and remark42 will write things into `<your_folder>/var` subdirectory.
  
> I wonder also if I have to change the volumes: - ./var:/srv/var at the end of the docker-compose.yml file,

No, no need to change. This `./var` declares relative path (to `docker-compose.yml`). I.e. if you start remark42 compose as `cd /srv/remark42 && docker-compose up -d` it will use your `/srv/remark42/var` to store all the info (comments, avatars, images and so on).

**Comment by joseph-vidal-rosset** [comment]
Thanks. I am impressed by your reactivity. My very last question is now about notification : do I need to get a telegram account to receive notifications? And if the reply is "no", what is the setup of notifications by email in docker-compose.yml ?

**Comment by umputun** [comment]
support for email notification is a work–in-progress (there are tickets about it as well as PR). As of now if you want to be notified you could use telegram

**Comment by joseph-vidal-rosset** [comment]
The jet lag explains the delay of my "Thanks". I am going to close this thread and I will search in the archives the post about email notification. I can make a suggestion that maybe can be useful to the developers of remark42. I will also write a detailed report of my installation (that I hope successful) that I plan to make today. Again, many thanks for your work and for your help.
