### ISSUE TITLE
email notifications: maybe isso (in python) could be helpful

### ISSUE THREAD

**Issue by joseph-vidal-rosset** [umputun/remark#461]
Hello, 
I really do not know if this suggestion is interesting, but I point out to the remark developers that isso (another comments free software) has a program in python that allows email notification, see isso here :  [https://github.com/posativ/isso](url) . Its works and the setup is quite easy: a sender gmail address  and a receiver gmail address , smtp.gmail.com 587 starttssl  , and that's it. 
I hope it helps, too bad if it is not the case.

**Comment by umputun** [comment]
#265 already dealing with email notifications.
