### ISSUE TITLE
[CI] goveralls send fails in forks

### ISSUE THREAD

**Issue by paskal** [umputun/remark#462]
[submit coverage](https://github.com/umputun/remark/blob/master/.github/workflows/ci-build.yml#L52-L64) step of GitHub actions `build` pipeline [fails in fork](https://github.com/paskal/remark/runs/288874529#step:8:1) because of the empty COVERALLS_TOKEN env variable. Error message:
```
flag needs an argument: -repotoken
```

Possible solution: we can skip this step if this variable is not set.

**Comment by umputun** [comment]
well, this not supposed to work in fork as fork is your own repo. If you want to submit coverage report you should link coveralls to yout repo and set secret COVERALLS_TOKEN

**Comment by umputun** [comment]
oh, I see what you mean. This faild not on the fork but on updated PR

**Comment by paskal** [comment]
For context: [this](https://github.com/umputun/remark/runs/288874642#step:8:1) is the build of PR code in this repo which failed.

**Comment by umputun** [comment]
I think this is some security-related limitation and PR can't access secrets in actions. Will be nice if you can investigate the issue and offer a solution or at least a workaround. Maybe @Smolevich can help with this

re: #433

**Comment by Smolevich** [comment]
From [Docs](https://help.github.com/en/github/automating-your-workflow-with-github-actions/virtual-environments-for-github-actions#creating-and-using-secrets-encrypted-variables):
 `secrets are not passed to the runner when a workflow is triggered from a forked repository.`

**Comment by Smolevich** [comment]
I think that @paskal can enable sync with fork repo in coveralls.io and add pass its repo token in secret. Or skip this step, but looks like as nice solution

**Comment by umputun** [comment]
@Smolevich it makes some sense I guess. Can you exclude the step publishing report, based on this (forked or not?) Maybe we can allow this step to fail, which also should do it

**Comment by umputun** [comment]
one more thing - on Travis we were able to publish coverage on PR requests and this info was useful. I.e. we could see if PR decreased coverage. Is this possible to do with actions somehow?

**Comment by Smolevich** [comment]
> @Smolevich it makes some sense I guess. Can you exclude the step publishing report, based on this (forked or not?) Maybe we can allow this step to fail, which also should do it

Maybe use this [mechanism](https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsif)

**Comment by umputun** [comment]
could be, can you PR with that `if` pls?

**Comment by paskal** [comment]
For context, I believe the problem [is not solvable at the moment](https://github.community/t5/GitHub-Actions/Token-permissions-for-forks-once-again/td-p/33839).

**Comment by umputun** [comment]
Wondering, how the official coveralls thingy supposed to work on PRs? https://github.com/marketplace/actions/coveralls-github-action

**Comment by paskal** [comment]
Interesting question, I found [a PR](https://github.com/SerayaEryn/fastify-session/pull/78) with coveralls plugin which successfully completed sending data to coveralls.
The difference between [their file](https://github.com/SerayaEryn/fastify-session/blob/d473133a3cfdaded2adf8e80b0b7c6313bbaf897/.github/workflows/ci.yml#L27-L31) and [ours](https://github.com/umputun/remark/blob/dff1e976041af8b5b09349fabc9882e9e5b813d1/.github/workflows/ci-build.yml#L52-L64):

```diff
-        with:
-          github-token: ${{ secrets.github_token }}
-          parallel: true
+      env:
+        COVERALLS_TOKEN: ${{secrets.COVERALLS_TOKEN}}
```
@Smolevich I wonder if we can switch to this `with` syntax, it seems that it doesn't have a restriction of `env` which is mentioned by link I provided previously.

**Comment by umputun** [comment]
with syntax is for plugins, or whatever those container called on gihub actions. Probably if we wrap goveralls into this thing it may help

**Comment by paskal** [comment]
I'll try to create a GitHub action for goveralls, I think it wouldn't be too complex.

**Comment by paskal** [comment]
If https://github.com/umputun/remark/pull/465 wouldn't help then GitHub action won't help as well. The magic part of coveralls plugin above is not the syntax but [GITHUB_TOKEN](https://help.github.com/en/github/automating-your-workflow-with-github-actions/authenticating-with-the-github_token#about-the-github_token-secret) usage.

**Comment by umputun** [comment]
is goverals even make use of `GITHUB_TOKEN` ?

**Comment by umputun** [comment]
a few days ago I played with the idea of using their action directly by converting coverage in a separate stage, see https://github.com/umputun/remark/blob/8494296b8588a6602e7dbd6798d52c469361a118/.github/workflows/ci-build.yml#L53

Probably it should work fine in PR (you can try in yours) but unfortunately, gcov2lcov is kind of odd and excludes branches too aggressively. For example if we have code like this:

```
if err := blah(foo, bar); err != nil {
  something we never reach
}
```

It will mark everything, including if itself as not covered. This is odd, unusual and confusing to someone reading the coverage report
