### ISSUE TITLE
Anonymous provider fails due to aud mismatch

### ISSUE THREAD

**Issue by umputun** [umputun/remark#463]
_triggered by https://github.com/umputun/remark/issues/385#issuecomment-549912484)_

It looks like a regression due to [this change](https://github.com/go-pkgz/auth/commit/6dfd65f26e95619274754cc8434abdf9c1dfd8f5). On remark42 side anonymous user gets "invalid site - site mismatch, not allowed to post to remark - 403 (4)"

**Comment by umputun** [comment]
@Reeywhaar - I think this is something (likely typo) on your side. In the token created by demo for anon I get really strange aud with "remark?from=....". The backend didn't care about it much, but with strict aud matching it breaks the auth flow completely.

The request you send seems to have a typo in(note the second `?`) 

 "https://demo.remark42.com/auth/anonymous/login?user=ssss&aud=remark?from=https%3A%2F%2Fdemo.remark42.com%2Fweb%2Fiframe.html%3FselfClose&site=remark"

**Comment by Reeywhaar** [comment]
oh, I see you've already added the commit :-)

**Comment by umputun** [comment]
used all my "search-and-replace" abilities ;) Hopefully, changed in the right place

**Comment by umputun** [comment]
hmm, it didn't help. still getting bad one 

`invalid site - site mismatch, "remark?from=https://demo.remark42.com/web/iframe.html?selfClose" not allowed to post to remark - 403 (4)`

maybe some other place should be changed too?

**Comment by Reeywhaar** [comment]
hm, just checked it, works fine for me if we speak of anonymous login

**Comment by Reeywhaar** [comment]
I noticed not along ago, that there could be difficulties with "127.0.0.1" and "localhost" on dev env.

**Comment by umputun** [comment]
I can't login, this part worked. But attempt to post fails on Forbidden. This is on demo site

**Comment by umputun** [comment]
could be safari caching. On fresh chrome it worked

**Comment by Reeywhaar** [comment]
oh, JWT here is wrong.

**Comment by umputun** [comment]
I guess this is a secret mismatch:

`auth failed, can't get token: failed to get token: can't parse token: signature is invalid`
