### ISSUE TITLE
GDPR compliance 

### ISSUE THREAD

**Issue by umputun** [umputun/remark#47]
remart42 is not a service but self-hosted solution, however, it should be a GDPR-compatible element of user's site. I'm not an expert in this regulation but looks like we may need some technical changes to be compliant:

1. Ability to remove user and all comments/replies. Currently, there is no such method in admin API and no way in protected API to request such deletion.
1. Example of privacy.html supplied with this service should be changed
1. Cookie banner?
1. Is there anything else we have to do?

**Comment by l13t** [comment]
afaik critical user data should be encrypted. i mean data which could be used to identify user (email, facebook_id or something similar).

**Comment by umputun** [comment]
@l13t IDs and IPs already encrypted. Email not even stored, and I'll try to exclude them from being transferred to me (probably fb and github only, google seems to treat it as ID). 

For admin part - there is nothing hosted separately in this service.

The goal of this ticket is not to make the service itself CDRP-complaint (there is no hosted service, except a demo page)  but to help users of remark42 to achieve such compliance.

**Comment by l13t** [comment]
aha. sorry for the misunderstanding.

**Comment by umputun** [comment]
1. Github oauth2 scope reduced to none (i.e. empty). It is the lowest possible scope, and I can't restrict it anymore. Still sends some extra information I don't need, but looks like this is the same info available from user's public profile.
1. Google scope changed to `https://www.googleapis.com/auth/userinfo.profile`. That eliminates user's email and keeps just a name, sub (numeric id), picture and some other basic fields. I'm not sure if it possible to ask for less info, looks like this is the minimal available scope.
1. FB scope `public_profile` still the same. I think this one is the most basic they have.

**Comment by umputun** [comment]
@igoradamenko - we have the API method (admin only) to perform such nuclear annihilation of the user, however, need some UI support for this. Adding admin-ui link/button to invoke it could be the minimal solution, however, I don't have any bright ideas how the user will communicate such request to us.

Even if they send us an email and ask "can you remove me, name=blah, id=github_blahblah" we don't have any method to verify if the user really owns this "account". I think we need a way to request such destruction as a part of authenticated API, and those request should be transferred to us somehow, maybe a new pair of methods "POST /deleteme" and "GET /deleteme"?

**Comment by umputun** [comment]
I think, there is a cheap way to provide verified delete of all user's info without dealing too much with the state, store and with a minimum of the new code:

1. UI hits smth like `POST /deleteme", and get a response as JSON body with the signed link
1. UI asks the user to email deletion request to an admin (his email will be added to `/config`) and button "send deleting request" will open his email client with populated "to". "subject" and "body". The body will include signed link and some text asking user to provide details (if he wants) but not to delete anything below some "====" line.
1. Admin gets email and clicks on a link which will trigger complete cleanup of all user info.

**Comment by umputun** [comment]
Pls note - https://github.com/umputun/remark/commit/4ba7fb20ae1e3b326afab2dbf586a33c4bd500c9 added support of exporting all info we know about user. This is a simple `GET /api/v1/userdata?site=site-id` and the result will be gz file. It needs a link in some place. Probably all those exotic extras we can put under some sub-menu/dropdown "more".

**Comment by umputun** [comment]
New, optional `session` parameter for `/login` restricts cookies to session-only. Should be part of the dialog in #54
