### ISSUE TITLE
Allow anonymous voting 

### ISSUE THREAD

**Issue by umputun** [umputun/remark#473]
Currently, anonymous users can't vote. This is not a bug but expected behavior as we had no way to prevent abuse in such a case. However, with #400 in place, we may allow it.

This is going to be a new param (disabled by default) and in case of votes IP check disabled, will show a warning in logs.

_triggered by #472_

**Comment by paskal** [comment]
Now there is an `anon_vote` option in `/config` endpoint and in case it's true, an anonymous user is allowed to vote.
What is missing is frontend support for it: currently, the anonymous user is always restricted from voting.
