### ISSUE TITLE
Two suggestions about new auth providers that could be nice to add

### ISSUE THREAD

**Issue by joseph-vidal-rosset** [umputun/remark#477]
Hello,
First suggestion : https://members.orcid.org/api/oauth/get-oauthauthorize
Second suggestion: https://docs.joinmastodon.org/api/authentication/
The first could be interesting for academics, the second is in my opinion far more interesting and valuable than Twitter (for obvious reasons). 
Best wishes, 
Jo.

**Comment by umputun** [comment]
thx for suggestions. Remark42 doesn't implement oauth/oauth2 by itself but leverages [go-pkgz/auth](https://github.com/go-pkgz/auth) library. So, it will be better to have such a tciket in go-pkgz/auth first. The integration of additional providers on remark42 level will be trivial as long as auth package supports it.

From the quick looks, it seems like your suggestions are typical oauth2 provider (i.e. should be possible to support without much headache), however, I'm not sure how popular those things and if it makes sense to support any of them as a part of auth package and remark42. I'm not sure either how Mastodon is "far more interesting and valuable than Twitter". The goal is to allow a typical internet user to log in and twitter is a much more popular platform. In this context "more interesting" doesn't really matter, but more popular is a thing.

**Comment by joseph-vidal-rosset** [comment]
> thx for suggestions. Remark42 doesn't implement oauth/oauth2 by itself but leverages go-pkgz/auth library. So, it will be better to have such a tciket in go-pkgz/auth first. The integration of additional providers on remark42 level will be trivial as long as auth package supports it.

Done. 

> From the quick looks, it seems like your suggestions are typical oauth2 provider (i.e. should be possible to support without much headache), however, I'm not sure how popular those things and if it makes sense to support any of them as a part of auth package and remark42. I'm not sure either how Mastodon is "far more interesting and valuable than Twitter". The goal is to allow a typical internet user to log in and twitter is a much more popular platform. In this context "more interesting" doesn't really matter, but more popular is a thing.

Hoping to convince you, two points to reply to your couple of remarks. 

1. Because Remark42 is an open source engine comment that you generously give to people that are free to install it for their own purpose, it is possible that some are interested to get for example academic comments to academic papers or notes. Webmaster that  are not interested are free to not including it in their docker-compose, as well as users that do not see the point are free to not log in ORCID (as well as other popular social medias). 
2. From a philosophical point of view, it seems to me fair that Remark42 that is a free and an open source software supports free and open source projects, e.g. Mastodon. _Mutatis mutandis_ , no doubt that Windows is more "popular" than GNU/Linux, but I claim that the later is "more interesting" than the former, and I would be surprised that you disagree. 

To not waste your time with philosophical discussions here, I close the topic. You know my address email if you are interested in going on.
