### ISSUE TITLE
auth failed, can't get token: token cookie was not presented

### ISSUE THREAD

**Issue by emathison** [umputun/remark#481]
In the logs, I see the following debug message:

[DEBUG] {middleware/auth.go:68 middleware.(*Authenticator).auth.func1} auth failed, can't get token: token cookie was not presented: http: named cookie not present

I'm using remark42 version 1.4.0 and domain1.com / comments.domain1.com

**Comment by umputun** [comment]
Is it causing any issue? I mean do you report this one as an indication of some problem? 

_Note: generally this message appears as UI checks login status and if the user not logged in, the backend will produce the message. This is expected_

**Comment by emathison** [comment]
I'm not experiencing any issues. I just thought it was unexpected. Thank you for the clarification.
