### ISSUE TITLE
Twitter auth not working for me

### ISSUE THREAD

**Issue by emathison** [umputun/remark#482]
I have both GitHub and Twitter configured as auth providers. However, only GitHub is working for me.

>    - AUTH_GITHUB_CID=1c...
>    - AUTH_GITHUB_CSEC=6d...
>    - AUTH_TWITTER_CID=Gg...
>    - AUTH_TWITTER_CSEC=vZ...

`docker exec container env` shows the proper values set

> AUTH_TWITTER_CSEC=vZ...
> AUTH_TWITTER_CID=Gg...

In the logs, I see that it creates GitHub OAuth 2, but not Twitter. There's no mention of Twitter in the logs anywhere.

> [INFO]  {provider/oauth2.go:59 provider.initOauth2Handler} init oauth2 service github

When I go to comments.domain1.com/auth/twitter/ it returns: 

> {"error":"provider twitter not supported"}

Any ideas?

**Comment by umputun** [comment]
I think you are using a stable (1.4) version. Twitter support wasn't part of 1.4 and, as of now, available in the master version only. In order to switch, you should change image in your docker-compose.yml to :master image, i.e. `image: umputun/remark42:master`

**Comment by emathison** [comment]
Thanks a lot! This was the issue.
