### ISSUE TITLE
Cursor sticks to the left when typing text (MS Edge)

### ISSUE THREAD

**Issue by tabakerov** [umputun/remark#484]
Microsoft Edge 44.18362.449.0
When I type text (at podcast.umputun,com and radio-t.com) it looks like "Home" button is pressed constantly (cursor always jumps to the beginning of the line) so text appears in right-to-left way.
See https://vimeo.com/377949461

**Comment by umputun** [comment]
@Reeywhaar any brilliant ideas what's wrong?
