### ISSUE TITLE
Prettify email notifications HTML

### ISSUE THREAD

**Issue by paskal** [umputun/remark#494]
Email notifications are merged but are not yet enabled and it's necessary to adjust the new comment notification template before we will be able to enable it.

When subscibed user get reply to their comment they get email notification currently which look like this:
<img width="722" alt="image" src="https://user-images.githubusercontent.com/712534/70975902-2a560b80-20ab-11ea-879a-ef6dcd2960de.png">

It should have a user avatar, and text of the comment it replies to. Also, it might be a good idea to add a date to both comments it in the same way it's done on the site:
<img width="843" alt="image" src="https://user-images.githubusercontent.com/712534/70976092-93d61a00-20ab-11ea-9ffb-06231375d315.png">

Here is how Disqus handles this.
<img width="722" alt="image" src="https://uploads.disquscdn.com/images/7e423eee4b5f4816f36acd53c49131f4877883e2b3a2d3ed31f01f3fd95a234c.png">

The code of the template which should be changed: https://github.com/umputun/remark/blob/d23d119d70e015d65aaf155713f615056181df96/backend/app/notify/email.go#L97-L115

New reply and parent comment parameters which you can use in the template:

https://github.com/umputun/remark/blob/d23d119d70e015d65aaf155713f615056181df96/backend/app/store/comment.go#L12-L30

https://github.com/umputun/remark/blob/d23d119d70e015d65aaf155713f615056181df96/backend/app/store/user.go#L16-L26

Please pick human-readable names for variables in your template, there is no problem translating `parent.Comment.User.Picture` to `parentUserAvatar` when passing to HTML template.

**Comment by StaroKep** [comment]
<img width="690" alt="Screen Shot 2019-12-29 at 01 27 35" src="https://user-images.githubusercontent.com/17280727/71550165-f64be600-29da-11ea-9d45-fe06f053e157.png">

Code:
1)https://paste.ofcode.org/kR3iDbUrHxPBJ8LfqwtSTd
2) https://paste.ofcode.org/t8ZKCFmY8KzGzhjpK66cC4

**Comment by paskal** [comment]
@StaroKep really nice job! Would you be so kind as to prepare PR request with these changes?

From the code part, I would suggest only removing empty lines and making `style` single-lined. If it would be necessary, I'll move the code to a separate file instead of having it inline now.

**Comment by umputun** [comment]
one thing we may want to modify in the template above - make the parent comment less visible somehow. I mean, the parent shouldn't be the same size/font as the reply. Maybe we can just make message font smaller and a little bit darker for the parent and this way the actual reply will be immediately recognizable.

**Comment by paskal** [comment]
Resolved in #550.
