### ISSUE TITLE
UI for email subscription

### ISSUE THREAD

**Issue by umputun** [umputun/remark#496]
With the backend part in place (thx to @paskal) we can integrate it on the UI side. This should be something similar to email-based login, i.e:

1. Add a link "subscribe to email notification"
1. Click on this link will ask for email and show confirmation dialog expecting a token
1. Token will be sent to the user by email, the same way as we send confirmations for email auth
1. Subscribed user should be able to unsubscribe from UI

API for email notifications [documented in the readme](https://github.com/umputun/remark#email-subscription) 

@Reeywhaar - let me know if you want to handle this one, should be very similar to email auth you did before.

**Comment by umputun** [comment]
related: #495 #494

**Comment by paskal** [comment]
1. https://www.mailgun.com/ is the easiest way to get a server for email notifications, docker-compose configuration for it would look similar to this:
    ```
            - NOTIFY_EMAIL_HOST=smtp.eu.mailgun.org
            - NOTIFY_EMAIL_USERNAME=postmaster@example.org
            - NOTIFY_EMAIL_PASSWORD=password
            - NOTIFY_EMAIL_FROM=notify@example.org
            - NOTIFY_EMAIL_PORT=465
            - NOTIFY_EMAIL_TLS=true
    ```
1. [remark.rest](https://github.com/umputun/remark/blob/master/backend/remark.rest) file has working examples of requests to run against local docker-compose setup, after which you will have chosen email account verified and receiving notifications.
1. A note on the implementation: when users subscribing to email notifications, they will get all replies to all their comments on the site.
1. A small fix to apply with implementing this feature: email verification currently have text _Copy and paste this text into “token” field on comments page_ — it should be changed to something like _on email verification page_ when it will be know how it will be named.
https://github.com/umputun/remark/blob/d23d119d70e015d65aaf155713f615056181df96/backend/app/notify/email.go#L128
    <img width="360" alt="image" src="https://user-images.githubusercontent.com/712534/70978789-b1f24900-20b0-11ea-8761-75b6aead641b.png">

**Comment by akellbl4** [comment]
@umputun I can do it. Where should be placed subscribe button?

**Comment by paskal** [comment]
Another note: `/config` endpoint now has `email_notifications` boolean property which tells UI if notifications interface should be enabled.

**Comment by umputun** [comment]
@akellbl4 sorry, missed your question. Thx for volunteering, appreciate it. 

This subscribe button (link?) should be around other subscriptions 

<img width="656" alt="6cdc9-202001-02144447-ln7nj" src="https://user-images.githubusercontent.com/535880/71692027-7b822280-2d6e-11ea-9399-cc48aa14d380.png">

In some other ticket, I have proposed to change the plain list of subscriptions to something under dropdown or whatever control makes sense. As far as I recall the problem on the UI side was how to make it mobile-friendly. Feel free to propose any improvements for this block, as of now all this "subscribe" part is way too visible for such a secondary functionality.

**Comment by akellbl4** [comment]
@umputun I made UI example, If it is good for you I will go to logic.
![2020-01-04 18 33 19](https://user-images.githubusercontent.com/2330682/71767798-2df9e700-2f21-11ea-8c28-859ee8bbbcbd.gif)

**Comment by paskal** [comment]
> 3\. A note on the implementation: when users subscribing to email notifications, they will get all replies to all their comments on the site.

Unfortunately at this very moment that’s the only variant of email subscription.

**Comment by paskal** [comment]
I would suggest having something like "Subscribe to <Thread via RSS><Site via RSS><Replies via RSS><Replies via Email>" which will decrease occupied space as well.

**Comment by akellbl4** [comment]
@paskal I missed your note.
Your suggestion makes sense and I think I need to add a note about subscription by email.

**Comment by akellbl4** [comment]
@umputun @paskal something like that?
![2020-01-04 22 55 48](https://user-images.githubusercontent.com/2330682/71771002-690e1180-2f45-11ea-9be0-9b9f61fefb02.gif)

**Comment by paskal** [comment]
LGTM, but I wonder how would it look and feel like from mobile.

**Comment by umputun** [comment]
yeah. I'd call "Email" as "Replies via email", or even better would make two sections with headers (RSS and Email) in each one

**Comment by akellbl4** [comment]
I think it is the best variant :)
![2020-01-04 23 36 33](https://user-images.githubusercontent.com/2330682/71771407-3404bd80-2f4b-11ea-80fa-f1c00803869e.gif)
![2020-01-04 23 37 05](https://user-images.githubusercontent.com/2330682/71771408-35ce8100-2f4b-11ea-9584-c3a5855589d3.gif)

**Comment by umputun** [comment]
nice

**Comment by akellbl4** [comment]
@paskal I wrote some code for sending email verification but I won't receive emails with a token. At the same time, the email login works fine.
You can checkout my code from [here](https://github.com/akellbl4/remark/tree/feature/496_ui-for-email-subscription) maybe I did something wrong. I am not sure.
