### ISSUE TITLE
Build for FreeBSD

### ISSUE THREAD

**Issue by noamross** [umputun/remark#497]
Hi, I'm trying to get Remark42 to work in a FreeBSD environment where I don't have docker. Unfortunately the standalone Linux binary doesn't work under FreeBSD (it dies at the first web request). Can you point me to how I might compile from source without Docker?

**Comment by umputun** [comment]
Hi. There are two ways to build binary remark42 from sources:

1.  the simplest way is a cross-compile build on any system supporting docker. Linux, Win, MacOS should do it. To run such a build with FreeBSD target you do `make OS=freebsd bin` and it will produce self-contained `remark42` file. Note: I just added support for such FreeBSD build in 3eacd6f20120f2cc0cfc1e38d532aec25a839bb0
1. You can also install all dependencies & toolchains and run everything manually, directly on the FreeBSD box. Frankly, I have no clue if this will even work on FreeBSD (never tried), but take a look at Dockerfile.artifacts, it will give you ideas what needed to be installed, i.e. go, npm and so on

_Attached a binary build I just made for FreeBSD (from the master). For the next release, it will be a part of attached binary artifacts_

[remark42.freebsd-amd64.tar.gz](https://github.com/umputun/remark/files/3978714/remark42.freebsd-amd64.tar.gz)

**Comment by noamross** [comment]
The FreeBSD binary works great, thank you!
