### ISSUE TITLE
Autosubmit on paste the token in inputs

### ISSUE THREAD

**Issue by akellbl4** [umputun/remark#538]
We have auth by verification via token and we know the length of the token.
It says that we can submit the form automatically by pasting token in input.

This feature can implement for email auth and email subscription.

**Comment by umputun** [comment]
> and we know the length of the token.

Not really, the token is JWT and can have different lengths for different users. We know token structure (i.e. could be possible to match with regex) but not the length.

**Comment by akellbl4** [comment]
@umputun good. If I am right, it looks like `^[A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.?[A-Za-z0-9-_.+/=]*$`

**Comment by H1D** [comment]
Anyways we can [easily](https://stackoverflow.com/a/38552302) parse JWT token and auto submit when it is valid.

**Comment by akellbl4** [comment]
@H1D thank you for the good advice ;)
