### ISSUE TITLE
Option to disable comments manually or by post's age

### ISSUE THREAD

**Issue by umputun** [umputun/remark#55]
Such functionality needs support on backend and UI (for manual on/off). Fist it will require a way to set and retrieve this info (admin only API) and also integrate into comment's controller. In addition, will need a way to report it as a part of `find` response and (maybe) `list` response.

Wich such API in place adding automatic disable, based on the age of the oldest comment in the thread and a button on UI side will be almost trivial.

**Comment by umputun** [comment]
backend changes in place.
 
No new calls needed to retrieve read-only post's status. The current result of `/find` call (tree mode only) extended with `PostInfo` (json: info) with `read_only`. If this flag is `true` we shouldn't allow any new comments/replies for the post.

Admin API has a new `PUT /readonly?site=siteID&url=post-url&ro=1` to set or reset RO status manually. Probably on UI side should be similar to block/unblock but on the post level.

**Comment by jackburg** [comment]
@umputun I'll take care of it

**Comment by jackburg** [comment]
I've added new "toggle" at the top-right corner, please take a look.

**disabling comments:**
![2018-07-11 00 05 34](https://user-images.githubusercontent.com/7156424/42537862-cbbe3542-849e-11e8-973b-e28f37474e1f.gif)

**enabling comments:**
![2018-07-11 00 05 58](https://user-images.githubusercontent.com/7156424/42537887-da599cf4-849e-11e8-90d8-b5ef0d16f167.gif)

**Comment by umputun** [comment]
LGTM
