### ISSUE TITLE
Release v1.5

### ISSUE THREAD

**Issue by umputun** [umputun/remark#557]
We are getting close to 1.5

I'd like to finish #447 (mostly good to go) and figure #556

**Comment by paskal** [comment]
My consideration is a small part of #447, [deprecation of single server option](https://github.com/umputun/remark/pull/447#discussion_r363231144) in favor of the new one: I don't mind having or not having this particular PR in release, but we should finalize list of deprecated options (which we suppose to drop in 1.7.0) before releasing 1.5.0.

If somebody is aware of anything which they want to change in terms of command-line options, that's the best time to raise their concerns.

Also aside from this particular release, I'm not happy with 6-months release cycle and I will be happy to have minor releases from time to time, as today's path from feature implementation to end users is incredebly long.

**Comment by paskal** [comment]
I think #564 and #560 (or it's counterpart #538) should be in the release as well.

**Comment by umputun** [comment]
released
