### ISSUE TITLE
Built in browser's search doesn't work

### ISSUE THREAD

**Issue by paskal** [umputun/remark#565]
With current "load when I see it" approach it's impossible to search on the comments page, as search on page (at least in Firefox) would show results only from a text which is visible on the user's screen.

This breaks user experience and causes all kinds of problems, for example [on this page](https://radio-t.com/p/2020/01/14/prep-685/) with news references users are reporting same news multiple times as they have no ability to check for it other than read all comments manually.

I don't know how hard would be to fix it, but I do think that it should be fixed at any cost.

**Comment by umputun** [comment]
this is a good point. I didn't know our rendering is that dynamic.

**Comment by umputun** [comment]
I don't think we have a good reason to render comments on-demand on a big screen. Back in days, it used to be complete render on desktops and i don't recall why UI switched to this smart render. Probably this was done by @Reeywhaar for some good reason, but I really don't recall all the details.

**Comment by Reeywhaar** [comment]
Yeah, this was done because as React doesn't work good with long tree/list structures. On demo https://remark42.com/demo/ page there were noticeable lag when you click "reply", change sorting (like 20 seconds delay) and so on. So I switched to rendering of comment only if it is in viewport. Otherwise it renders dummy block (`<div></div>`).

Another good thing is that all images also render lazily.

But yeah, searching sucks.

**Comment by akellbl4** [comment]
@Reeywhaar do you made any benchmarks connected with it?

**Comment by Reeywhaar** [comment]
No, it was noticeable difference. You can try and disable it.

**Comment by paskal** [comment]
Is it possible to render whatever the user looks at the moment, but don't lose anything rendered so far? That way sort speed and all other things should be fine, I think that's similar to how Reddit works.

**Comment by Reeywhaar** [comment]
This will not solve the problem with searching, and will not gain anything.

I think that we can render dummy including comments message. As a compromise. But we'll lose lazy image loading, though it was side effect. If we need lazy loading, I think t can be made separately. Once concern is that comment's text itself can be complex structure (tables, images).

**Comment by paskal** [comment]
From Reddit I won't expect search from all comments because I know it won't load past first ~50 before I reach the end of the page, however, I know that I can search through whatever is loaded so far as soon as I've seen it once.

For Remark it doesn't work like that: I see lazy loading, but after scrolling to the very bottom I still can't search the data I've seen so far. This is an expected behavior for me.

**Comment by Reeywhaar** [comment]
Okay, let's try your solution.
