### ISSUE TITLE
Bug in Web Demo | Voting error: You have reached maximum request limit.

### ISSUE THREAD

**Issue by akivaron** [umputun/remark#587]
This bug occurs when I try to click the up vote and down vote too fast, the numbers start to change +2 and become normal and then an error vote appears

![Screenshot from 2020-01-30 11-58-45](https://user-images.githubusercontent.com/9086506/73421376-3abefe80-4358-11ea-849e-a40e600ce682.png)

![Screenshot from 2020-01-30 12-03-33](https://user-images.githubusercontent.com/9086506/73421487-a3a67680-4358-11ea-913d-23cbce2b872c.png)

**Comment by umputun** [comment]
This is not a bug, but expected behavior. There is a parameter `UPDATE_LIMIT`(default 1 per 2 seconds) and the user can change it to whatever needed.
