### ISSUE TITLE
<nil> as name when Name not set in github profile

### ISSUE THREAD

**Issue by 23ua** [umputun/remark#6]
Maybe use a username if name is not set?
<img width="1065" alt="screen shot 2018-05-12 at 20 59 39" src="https://user-images.githubusercontent.com/2116934/39960229-bcacea4e-5627-11e8-87b7-2e651362151b.png">
<img width="680" alt="screen shot 2018-05-12 at 21 00 01" src="https://user-images.githubusercontent.com/2116934/39960231-be7693f2-5627-11e8-9a0e-8d8a0577fb42.png">

**Comment by umputun** [comment]
In this case, github api returns string `<nil>` as user.   I have added the fix to use login name for such cases. Pls note - to see the fix you need to re-login.

**Comment by 23ua** [comment]
Thanks, the fix worked, although the name in the old comment didn't change.
I assume this is ok since changing the name in github doesn't affect old comments in other cases as well.
