### ISSUE TITLE
annoying "back" button behaviour

### ISSUE THREAD

**Issue by cdracm** [umputun/remark#62]
1. go to https://radio-t.com/p/2018/05/26/podcast-599/#remark42__comment-1160825e-ee76-46b4-8a3f-5821d621a86a
2. marvel at the umputun wisdom
3. press "back" browser button. Nothing happens. Press back again and curse. Now you are back. Finally!

(there must be some redirections going on behind the scenes which prevent "back" button from going back)

**Comment by umputun** [comment]
not sure if this is really what annoying, but unusual for sure. @igoradamenko probably due to anchor navigation?

**Comment by igoradamenko** [comment]
Closed by #71.
