### ISSUE TITLE
Does remark42 comments help with SEO and search?

### ISSUE THREAD

**Issue by matrixik** [umputun/remark#68]
Hi, thank you for working on this.

I don't have much knowledge about how Google Search or other search engines work with Javascript.
So I would like to ask if comments are visible in search results?

More info from other commenting system: https://faq.remarkbox.com/d1f50998-bb29-11e7-951f-040140774501/do-remarkbox-comments-help-with-seo-and-search

**Comment by umputun** [comment]
I'm not an expert in SEO, but basically, remark42 serves robots.txt, like [this one](https://demo.remark42.com/robots.txt) allowing search engines to index comments. 

No idea what else can be done to make it google-friendly.

**Comment by arogulin** [comment]
Unfortunately, Google is not able to see comments loaded within iframe **by javascript**. You can verify it with the following queries:
1. [This one will find unique text on the page](https://www.google.com/search?q=%22%D0%9C%D0%B0%D0%B9+22%2C+2018+-+1527004331%22+site%3Aradio-t.com)
2. [This one will not find unique text from one of the comment on the same page](https://www.google.com/search?q=%22%D0%9D%D0%B5%D0%B1%D0%BE%D0%BB%D1%8C%D1%88%D0%BE%D0%B5+%D1%81%D1%80%D0%B0%D0%B2%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5+%D0%BF%D0%BE%D1%81%D0%BB%D0%B5%D0%B4%D0%BD%D0%B8%D1%85+%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D0%B9%22+site%3Aradio-t.com)

So, the content in these comments will never help to bring new visitors from search engines.

**Comment by matrixik** [comment]
Then I'm not sure what https://remarkbox.com is doing to have them indexed because from short look into Firefox inspector looks like they also use iframe.
Example from the link I posted in first message: 
[Link to comment from article](https://russell.ballestrini.net/filtering-aws-resources-with-boto3/#0f7b334e-0489-40bd-948d-feb9ffcea1f7)
[And google search](https://www.google.com/search?num=30&source=hp&q=site%3Arussell.ballestrini.net+Thanks+Russell!+The+AWS+docs+don%27t+always+have+all+the+sample&oq=site%3Arussell.ballestrini.net+Thanks+Russell!+The+AWS+docs+don%27t+always+have+all+the+sample)

**Comment by umputun** [comment]
google search console in the section "fetch as google" shows all comments. I don't think "Google is not able to see comments loaded within iframe by javascript" is a correct conclusion and the reason why the second query found nothing it is because I have enabled robots to access to comments a day ago. I tend to believe it will be searchable as soon as they reindex those pages.

**Comment by matrixik** [comment]
Oh, that's great. Then I think this issue could be closed.
@umputun Could you also add this info to the README?

**Comment by umputun** [comment]
google reindexed and it works as expected. For example, [this query](https://www.google.com/search?source=hp&ei=YgwYW-OzIoOijwSNia-QBg&q=%22%D1%81+%D1%82%D0%B2%D0%BE%D0%B8%D0%BC+%D0%BE%D0%BF%D1%82%D0%B8%D0%BC%D0%B8%D0%B7%D0%BC%D0%BE%D0%BC+%D0%BF%D1%80%D0%BE%D1%81%D1%82%D0%BE+%D0%B2+%D0%BA%D0%BE%D1%81%D0%BC%D0%BE%D1%81+%D0%BD%D0%B0%D0%B4%D0%BE+%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA%D0%B0%D1%82%D1%8C%2C+%D0%BC%D0%BE%D0%B6%D0%BD%D0%BE+%D0%B1%D0%B5%D0%B7+%D1%81%D0%BA%D0%B0%D1%84%D0%B0%D0%BD%D0%B4%D1%80%D0%B0%22&oq=&gs_l=psy-ab.1.0.35i39k1l6.0.0.0.15307.4.1.0.0.0.0.0.0..1.0....0...1..64.psy-ab..3.1.62.6...62.23mk4xyP10s) runs on the comment text just fine

**Comment by arogulin** [comment]
Yeah, both queries from my comment show results now, so Google does execute javascript. When I was learning SEO last time (7 years ago), there were only rumors that Google is working on it. Good to know they have it done! Lack of SEO support from javascript comment engines was the only obstacle for me to use them.
