### ISSUE TITLE
Default sort displayed incorrectly on first sign in

### ISSUE THREAD

**Issue by 23ua** [umputun/remark#7]
After first sign in for a given browser "Sort by Best" is displayed in the interface but actual order appears to be "By oldest".

<img width="712" alt="screen shot 2018-05-12 at 21 11 41" src="https://user-images.githubusercontent.com/2116934/39960354-fa4d11c4-5629-11e8-9724-109ddf068d8c.png">

In order for the sort param "By Best" to work, you need to select some other order and only after that "By Best" again.

In the url of a request that fetches comments param `sort` equals to `null`:
```
https://demo.remark42.com/api/v1/find?url=https://remark42.com/demo/&sort=null&format=tree&site=remark
````

**Comment by igoradamenko** [comment]
Fixed.

Thanks!
