### ISSUE TITLE
Show more may prevent google's rendering for they search index

### ISSUE THREAD

**Issue by umputun** [umputun/remark#72]
I'm not sure if Google is smart enough to click "more" on they crawler but I suspect they are not. At least according to "Fetch/render as Google" they show comments on the first page only.

Can we somehow render it for google bots without "Show more"? I'm not even sure what side is this and how UI can even differentiate between normal request and those triggered by Google robots. If this can't be detected purely on JS side I can add a flag in the server response, like `robots: true` as a part of tree response

**Comment by umputun** [comment]
related to #68

**Comment by Nihisil** [comment]
@umputun You can check User-Agent on the server side to detect was it search engine bot or user: `/bot|google|baidu|bing|msn|duckduckbot|teoma|slurp|yandex/i` 

And if it is a search engine, just return all comments.

**Comment by umputun** [comment]
@Nihisil client side already requesting all comments and this "show more" is totally UI thingy

**Comment by umputun** [comment]
With this change https://github.com/umputun/remark/issues/25#issuecomment-396079125 we don't hide comments on a desktop anymore and "Fetch as Google (desktop)" can see them all. However, I'm not sure how exactly Google builds the index in such case as "fetch mobile" won't see them all.

<img width="182" alt="ecewf-201806-16125251-idoyu" src="https://user-images.githubusercontent.com/535880/41501149-36d13b8e-7164-11e8-916f-747d84903b9b.png">
