### ISSUE TITLE
Logo design proposal

### ISSUE THREAD

**Issue by Tobaloidee** [umputun/remark#75]
Hi Sir @umputun good day! I am a graphics designer and i want to contribute to your project by designing a logo for it to have an image representation. I will be doing it for free as my gift to the project.Just let me know if i can start or you are permitting me to do so. Thanks and best regards! 

- [Tobaloidee](https://github.com/Tobaloidee)

**Comment by umputun** [comment]
thx, will be nice to have a decent logo.

**Comment by Tobaloidee** [comment]
I will show it here asap Sir..thanks!

**Comment by Tobaloidee** [comment]
Here it is Sir, 

concept: minimal design consists of Comment shape with "R" for remark and gray dots to convey "to type" message in a comment


icon
![r42-01](https://user-images.githubusercontent.com/36028424/41186973-0e358612-6bd3-11e8-827d-2e6458c7838b.png)


logotypes
![r42-02](https://user-images.githubusercontent.com/36028424/41186962-f00baf0e-6bd2-11e8-9e56-458827375597.png)

**Comment by umputun** [comment]
Thx for the logo. Sorry, but I don't like it. I can't even explain what exactly I didn't like here, maybe this is not as minimal as I want, or something else. However, both logo colors, shape and fonts not what I had in mind.

**Comment by Tobaloidee** [comment]
do you have a color preference and idea that you want Sir? can i still make another variations?
