### ISSUE TITLE
Add configuration file

### ISSUE THREAD

**Issue by umputun** [umputun/remark#76]
We are getting too many parameters. Currently they mostly unions, but even know some of them related to particular implementations, like bolt parameters. Some, like oauth2 secrets and id repeated for multiple providers. And finally, for security reason, I'd like to remove sensitive settings like `SECRET` from the environment.

The plan is to add some `config.yml` and make it mapped to config structure. https://github.com/jinzhu/configor seems to be a good fit allowing yaml, toml and json

**Comment by matrixik** [comment]
I think https://github.com/spf13/viper have more functionality (like live watching and re-reading of config files (optional))

**Comment by umputun** [comment]
I have considered viper, but it felt too big and too much code for what I need. Technically even direct yaml parser will do almost all I want, but configor adds small and useful extras, like default values and required fields.

**Comment by umputun** [comment]
Tried this config file approach and didn't like the result. Figured a way to structure parameters with `go-flags` and it looks much better and less confusing.
