### ISSUE TITLE
Simultaneous votes can lead to vote loss

### ISSUE THREAD

**Issue by asnelzin** [umputun/remark#77]
If two (or more) users vote for one comment simultaneously it can lead to vote loss for one of the users.

Not sure if it's crucial bug, but seems not very good.

**Comment by umputun** [comment]
This race was due to lack of any sync in `service.Vote`. Added lock on votes and a test to confirm the fix.

**Comment by asnelzin** [comment]
Is in-memory locking is still a solution for distributed remark deployment? I think, `service.Vote` should be an engine level operation, so it could use DB features like transactions.
