### ISSUE TITLE
Show help about markdown formatting 

### ISSUE THREAD

**Issue by umputun** [umputun/remark#8]

**Comment by jackburg** [comment]
Any thoughts where we can get good example?

**Comment by igoradamenko** [comment]
I think SO has an interesting help about markdown: https://stackoverflow.com/questions/ask. They have some sections with description for the main tags.

![image](https://user-images.githubusercontent.com/6537798/42814832-2ad207fa-89ce-11e8-9ff4-2d2b1cca9480.png)

**Comment by umputun** [comment]
it looks nice, maybe too fancy. Giltab has it much simpler, just a link to 
https://gitlab.com/help/user/markdown 

<img width="524" alt="uf0d8-201807-17112056-hvxk4" src="https://user-images.githubusercontent.com/535880/42831294-941e09a4-89b3-11e8-93fe-8f7b431121ab.png">

**Comment by umputun** [comment]
@jackburg can you just get giltab's and remove all things we don't support?

**Comment by umputun** [comment]
or even simpler one - https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

**Comment by jackburg** [comment]
Sure!

**Comment by umputun** [comment]
@jackburg pinging ;) any chance you could add it beforе we release 1.1?

**Comment by jackburg** [comment]
@umputun I think I need few more days to accomplish it. Is it ok?

**Comment by umputun** [comment]
sure, thx

**Comment by jackburg** [comment]
Ok, got it

**Comment by jackburg** [comment]
@umputun Please take a look, what do you think about link location?

![image](https://user-images.githubusercontent.com/7156424/44168858-43c3fd80-a0db-11e8-848a-de12112f9cc5.png)

**Comment by jackburg** [comment]
@umputun should we open some kind of pop-up here (not actual window, just mimic) or we could host some simple html file with all markdown features we support on official Remark website and place link to this file here, what do you think?

**Comment by Guria** [comment]
@jackburg official remark wouldn't fit here since we can face with version mismatch of what installed and latest on official website

**Comment by Guria** [comment]
but it could be still html hosted near iframe.html

**Comment by igoradamenko** [comment]
I've merged #194 in ab6bfff, but let's not close this issue now, because @umputun had some comments about improving description: https://github.com/umputun/remark/pull/194#issuecomment-417950812.

I will check later how we can improve it.

**Comment by Reeywhaar** [comment]
seems to be fixed
