### ISSUE TITLE
PageUp in textarea bug

### ISSUE THREAD

**Issue by mykmykpet** [umputun/remark#80]
When textarea contains at least one char and PageUp pressed — comments container moves left.
Look video:
[![](https://img.youtube.com/vi/uFRB9jS91FI/0.jpg)](https://youtu.be/uFRB9jS91FI)
Chrome 67.0.3396.87 64-bit

**Comment by igoradamenko** [comment]
PRs are welcome :-)

**Comment by nini** [comment]
Applying `position: fixed` to [iframe](https://github.com/umputun/remark/blob/master/web/iframe.html#L10)  would resolve the issue, although I'm not sure why it's happening to Chrome.

**Comment by Guria** [comment]
It is auth-panel__select for some reason overflows container. Setting width: 100% helps.
Will fix soon
