### ISSUE TITLE
Gitlab/Hugo/Netlify Integration

### ISSUE THREAD

**Issue by pharbod** [umputun/remark#81]
Currently I am running a github static blog with Gitlab, Hugo and Netlify. How can I  setup remark?

**Comment by umputun** [comment]
remark42 is a self-hosted service, so the first thing you should host it someplace. It can be, for example, DigitalOcean droplet or AWS Instance or GCE or any other place like this. Next, you start the container as described in the readme and add widgets for comments, counters, and the recent comments.

You can see this [commit](https://github.com/radio-t/radio-t-site/commit/55c2f4eaacd531685a6b4d4b2cd1ef2c6799220a) integrating remark42 into real Hugo site https://radio-t.com

_Pls note – we already have #27 about very similar thing_
