### ISSUE TITLE
Avatar caching issues

### ISSUE THREAD

**Issue by anatolym** [umputun/remark#85]
There's an issue with avatar storing flow and client-side caching.
### Preconditions
1. Remark downloads user avatar from a provider every time on login.
1. Avatar is always saved to avatar store with the same name: `hash(userID) + ".image"` regardless the actual content.
1. Remark uses `Cache-Control` and `Etag` headers for GET avatar requests which enables client-side caching.
So far `Cache-Control:max-age=2592000` requires to keep avatar for 30 days. And `Etag` is always equal to avatar's file name (from 2nd clause).
1. Each comment of a user has it's own copy of user struct (including avatar URL) relevant on the comment creating moment.

### The problem
There's a scenario:
1. User logs in using some provider `P`, Remark saves avatar to file `A1`.
1. User gets avatar from Remark, user's browser starts keeping avatar for 30 days and `Etag` header `E1`.
1. Users changes avatar in provider `P`, logs out from Remark and logs in back again. Remark gets updated avatar from provider `P` and saves it with the same file name `A1`.
1. User doesn't see updated avatar.
1. After 30 days avatar cached on client-side expires, client sends `If-None-Match` header with value `E1`. Remark compare `E1` against the same `E1` and returns HTTP code 304 "StatusNotModified". Client prolongs avatar TTL and keeps using old avatar.

#### 1. Fix `Etag` and decrease client-side TTL for avatar
If we want to keep user avatar in a file with the same name, we should fix caching. So for `Etag` we could use last modified time of an avatar file (`os.FileInfo.ModTime()`).
As for TTL github uses 5 min TTL for user avatars.

#### 2. Use versioning in avatar url
Web-browsers see such URL as a different resources and are forced to reload it:

* `/api/v1/avatar/abc.image`
* `/api/v1/avatar/abc.image?v=111`
* `/api/v1/avatar/abc.image?v=222`

The cheap solution for us would be to use current unix timestamp as a version of avatar here
https://github.com/umputun/remark/blob/master/app/rest/proxy/avatar.go#L64

(Github uses such versioning for avatars too.)

This approach would allow us to force browsers to reload content of updated avatar in new comments.
But at the same time browsers will keep showing old avatar image in old comments.

#### 3. Create different avatar files for each login
I actually implemented this option first and than realized that this was not working. The main reason is that each comment has user model with old avatar.

@umputun, what do you think?

**Comment by umputun** [comment]
Option 2 won't work for the same reason as option 3 - avatar URL is a part of immutable (well, kind of immutable) stored comment. Generally, it is possible to rewrite avatar's URL on the server side and append `v=12345`  in the rest controller, but it is not clear how the server will even know "version change event" for all other users, i.e. not the one who changed his own avatar.

I think we should go with option 1. Probably we want to add a new method like ID or Hash to `AvatarStore` which will return a different value for different content. For `FSAvatarStore` implementation file's modification time (or hash of this time) will do it. And, as you suggested, we will use this value as Etag and short TTL.
