### ISSUE TITLE
Add ability to ban user for limited time

### ISSUE THREAD

**Issue by umputun** [umputun/remark#88]
From the experience of running remark42 in the real life, I have seen a need to ban a user temporarily. We don't have any automatic way to do it, but if we extend `store.BlockedUser` with TTL and add support of such TTL to `IsBlocked` this will do it.   

In addition, we will need UI to support such selection of ban-type as well as an indication of ban type and TTL in the list of blocked users

**Comment by umputun** [comment]
The backend change completed. For frontend we need a couple of minor changes:

1. Ability to select ban duration. Could be just a list of "permanent, 1 day, 7 days, 30 days."
1. In the list of banned users show this info as "banned until." 

@igoradamenko - feel free to add necessary info for contributors if my description incomplete or confusing. Probably you can set it to "first good issue" if this is really as simple as I think.

**Comment by jackburg** [comment]
Господа хорошие, позвольте мне закрыть данный ишью.

**Comment by Guria** [comment]
@jackburg Use English please.

If I correctly understand, you want to make a UI part of this, right?
Feel free to make a PR.

**Comment by jackburg** [comment]
Ok got it.

**Comment by umputun** [comment]
Looks good to me
