### ISSUE TITLE
Caching issue, probably nginx proxy related

### ISSUE THREAD

**Issue by umputun** [umputun/remark#9]
Looks like configuration with nginx proxy has no caching for anything I'd like to be cached. At least I can see way too many hits to static files, like images, js and so on.

edit: to clarify the caching nature - this is about browser's caching, not the server-side.

**Comment by paralainer** [comment]
Isn't it related to `s.Cache.Flush()` calls on `POST /comment` (and in some other places)?

**Comment by umputun** [comment]
no, unrelated. this issue is about caching of static assets on the browser side. 

The flush invalidates server cache on updates, but this is a different kind of cache.

**Comment by umputun** [comment]
added cache-control for `/api/v1/avatar`
