### ISSUE TITLE
Separate frontend & backend

### ISSUE THREAD

**Issue by igoradamenko** [umputun/remark#99]
I think we should separate frontend & backend. Right now fronted is just a folder `web` inside a project, which looks a bit awkward. And we have a lot of go's files inside a project root, etc.

@umputun, what do you think about explicit separation? Like folders `frontend` and `backend` in project root? Is it possible for your part, or not?

**Comment by umputun** [comment]
Yeah, planned to do this. We can start by renaming `app` to `backend` and `web` to `frontend`. On my side, this will need some refactoring since go kind of sensitive to the path, but not a big deal.

**Comment by umputun** [comment]
the backend code was moved to `backend` top-level directory

**Comment by umputun** [comment]
@igoradamenko - you can rename `web` as you ready

**Comment by umputun** [comment]
@Reeywhaar - how hard is to rename `web` to `frontend`? Obviously not that critical, but will be nice to have backend and frontend directories

**Comment by Reeywhaar** [comment]
I think it's possible
